// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BCMOKFHJMPM.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from BCMOKFHJMPM.proto</summary>
  public static partial class BCMOKFHJMPMReflection {

    #region Descriptor
    /// <summary>File descriptor for BCMOKFHJMPM.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BCMOKFHJMPMReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFCQ01PS0ZISk1QTS5wcm90bxoRT09FTUlCRk5MTEQucHJvdG8aEUxBSUxO",
            "SUdGUE9PLnByb3RvIssDCgtCQ01PS0ZISk1QTRIPCgdwb29sX2lkGAkgASgN",
            "EhMKC0JOT0xETkJNSkhGGAQgASgNEhMKC0ZIT0xGRE9OT0lJGAUgASgIEhMK",
            "C0RHQUxDTUZJREZQGAwgASgNEhQKC1BKREZCUEJNQkJBGPIEIAEoCRITCgtP",
            "TUdLSkxKSUhMSBgNIAEoBBITCgtKT0pOREdCRUpFSxgKIAEoBBIUCgtKTEVH",
            "UE5JSE1KRBjoASABKAkSIQoLRUJBQkJFSklQSk4YByADKAsyDC5MQUlMTklH",
            "RlBPTxIhCgtLR0JFSktOQ0xGSxgCIAMoCzIMLk9PRU1JQkZOTExEEhMKC0pH",
            "TklITEpGSlBQGAEgASgNEiEKC0lGS0ZFUEtITEdOGAYgAygLMgwuT09FTUlC",
            "Rk5MTEQSEwoLRERJQkVGTUlMTVAYQSABKAkSIQoLQ0pGTUFJQUtFTkwYCyAD",
            "KAsyDC5PT0VNSUJGTkxMRBIhCgtKQ0tOR0ZKRUVHSRgPIAMoCzIMLk9PRU1J",
            "QkZOTExEEhMKC0VCT09MR05BQ0pKGAMgASgEEhMKC0RHRVBNS0ZGT0FCGA4g",
            "ASgNEhMKC0xKSk1MRUlPSUZFGAggASgNQh6qAhtFZ2dMaW5rLkRhbmhlbmdT",
            "ZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.OOEMIBFNLLDReflection.Descriptor, global::EggLink.DanhengServer.Proto.LAILNIGFPOOReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.BCMOKFHJMPM), global::EggLink.DanhengServer.Proto.BCMOKFHJMPM.Parser, new[]{ "PoolId", "BNOLDNBMJHF", "FHOLFDONOII", "DGALCMFIDFP", "PJDFBPBMBBA", "OMGKJLJIHLH", "JOJNDGBEJEK", "JLEGPNIHMJD", "EBABBEJIPJN", "KGBEJKNCLFK", "JGNIHLJFJPP", "IFKFEPKHLGN", "DDIBEFMILMP", "CJFMAIAKENL", "JCKNGFJEEGI", "EBOOLGNACJJ", "DGEPMKFFOAB", "LJJMLEIOIFE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BCMOKFHJMPM : pb::IMessage<BCMOKFHJMPM>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BCMOKFHJMPM> _parser = new pb::MessageParser<BCMOKFHJMPM>(() => new BCMOKFHJMPM());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BCMOKFHJMPM> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.BCMOKFHJMPMReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BCMOKFHJMPM() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BCMOKFHJMPM(BCMOKFHJMPM other) : this() {
      poolId_ = other.poolId_;
      bNOLDNBMJHF_ = other.bNOLDNBMJHF_;
      fHOLFDONOII_ = other.fHOLFDONOII_;
      dGALCMFIDFP_ = other.dGALCMFIDFP_;
      pJDFBPBMBBA_ = other.pJDFBPBMBBA_;
      oMGKJLJIHLH_ = other.oMGKJLJIHLH_;
      jOJNDGBEJEK_ = other.jOJNDGBEJEK_;
      jLEGPNIHMJD_ = other.jLEGPNIHMJD_;
      eBABBEJIPJN_ = other.eBABBEJIPJN_.Clone();
      kGBEJKNCLFK_ = other.kGBEJKNCLFK_.Clone();
      jGNIHLJFJPP_ = other.jGNIHLJFJPP_;
      iFKFEPKHLGN_ = other.iFKFEPKHLGN_.Clone();
      dDIBEFMILMP_ = other.dDIBEFMILMP_;
      cJFMAIAKENL_ = other.cJFMAIAKENL_.Clone();
      jCKNGFJEEGI_ = other.jCKNGFJEEGI_.Clone();
      eBOOLGNACJJ_ = other.eBOOLGNACJJ_;
      dGEPMKFFOAB_ = other.dGEPMKFFOAB_;
      lJJMLEIOIFE_ = other.lJJMLEIOIFE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BCMOKFHJMPM Clone() {
      return new BCMOKFHJMPM(this);
    }

    /// <summary>Field number for the "pool_id" field.</summary>
    public const int PoolIdFieldNumber = 9;
    private uint poolId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PoolId {
      get { return poolId_; }
      set {
        poolId_ = value;
      }
    }

    /// <summary>Field number for the "BNOLDNBMJHF" field.</summary>
    public const int BNOLDNBMJHFFieldNumber = 4;
    private uint bNOLDNBMJHF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BNOLDNBMJHF {
      get { return bNOLDNBMJHF_; }
      set {
        bNOLDNBMJHF_ = value;
      }
    }

    /// <summary>Field number for the "FHOLFDONOII" field.</summary>
    public const int FHOLFDONOIIFieldNumber = 5;
    private bool fHOLFDONOII_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool FHOLFDONOII {
      get { return fHOLFDONOII_; }
      set {
        fHOLFDONOII_ = value;
      }
    }

    /// <summary>Field number for the "DGALCMFIDFP" field.</summary>
    public const int DGALCMFIDFPFieldNumber = 12;
    private uint dGALCMFIDFP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DGALCMFIDFP {
      get { return dGALCMFIDFP_; }
      set {
        dGALCMFIDFP_ = value;
      }
    }

    /// <summary>Field number for the "PJDFBPBMBBA" field.</summary>
    public const int PJDFBPBMBBAFieldNumber = 626;
    private string pJDFBPBMBBA_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PJDFBPBMBBA {
      get { return pJDFBPBMBBA_; }
      set {
        pJDFBPBMBBA_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OMGKJLJIHLH" field.</summary>
    public const int OMGKJLJIHLHFieldNumber = 13;
    private ulong oMGKJLJIHLH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong OMGKJLJIHLH {
      get { return oMGKJLJIHLH_; }
      set {
        oMGKJLJIHLH_ = value;
      }
    }

    /// <summary>Field number for the "JOJNDGBEJEK" field.</summary>
    public const int JOJNDGBEJEKFieldNumber = 10;
    private ulong jOJNDGBEJEK_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong JOJNDGBEJEK {
      get { return jOJNDGBEJEK_; }
      set {
        jOJNDGBEJEK_ = value;
      }
    }

    /// <summary>Field number for the "JLEGPNIHMJD" field.</summary>
    public const int JLEGPNIHMJDFieldNumber = 232;
    private string jLEGPNIHMJD_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string JLEGPNIHMJD {
      get { return jLEGPNIHMJD_; }
      set {
        jLEGPNIHMJD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "EBABBEJIPJN" field.</summary>
    public const int EBABBEJIPJNFieldNumber = 7;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.LAILNIGFPOO> _repeated_eBABBEJIPJN_codec
        = pb::FieldCodec.ForMessage(58, global::EggLink.DanhengServer.Proto.LAILNIGFPOO.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.LAILNIGFPOO> eBABBEJIPJN_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.LAILNIGFPOO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.LAILNIGFPOO> EBABBEJIPJN {
      get { return eBABBEJIPJN_; }
    }

    /// <summary>Field number for the "KGBEJKNCLFK" field.</summary>
    public const int KGBEJKNCLFKFieldNumber = 2;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> _repeated_kGBEJKNCLFK_codec
        = pb::FieldCodec.ForMessage(18, global::EggLink.DanhengServer.Proto.OOEMIBFNLLD.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> kGBEJKNCLFK_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> KGBEJKNCLFK {
      get { return kGBEJKNCLFK_; }
    }

    /// <summary>Field number for the "JGNIHLJFJPP" field.</summary>
    public const int JGNIHLJFJPPFieldNumber = 1;
    private uint jGNIHLJFJPP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint JGNIHLJFJPP {
      get { return jGNIHLJFJPP_; }
      set {
        jGNIHLJFJPP_ = value;
      }
    }

    /// <summary>Field number for the "IFKFEPKHLGN" field.</summary>
    public const int IFKFEPKHLGNFieldNumber = 6;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> _repeated_iFKFEPKHLGN_codec
        = pb::FieldCodec.ForMessage(50, global::EggLink.DanhengServer.Proto.OOEMIBFNLLD.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> iFKFEPKHLGN_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> IFKFEPKHLGN {
      get { return iFKFEPKHLGN_; }
    }

    /// <summary>Field number for the "DDIBEFMILMP" field.</summary>
    public const int DDIBEFMILMPFieldNumber = 65;
    private string dDIBEFMILMP_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DDIBEFMILMP {
      get { return dDIBEFMILMP_; }
      set {
        dDIBEFMILMP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CJFMAIAKENL" field.</summary>
    public const int CJFMAIAKENLFieldNumber = 11;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> _repeated_cJFMAIAKENL_codec
        = pb::FieldCodec.ForMessage(90, global::EggLink.DanhengServer.Proto.OOEMIBFNLLD.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> cJFMAIAKENL_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> CJFMAIAKENL {
      get { return cJFMAIAKENL_; }
    }

    /// <summary>Field number for the "JCKNGFJEEGI" field.</summary>
    public const int JCKNGFJEEGIFieldNumber = 15;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> _repeated_jCKNGFJEEGI_codec
        = pb::FieldCodec.ForMessage(122, global::EggLink.DanhengServer.Proto.OOEMIBFNLLD.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> jCKNGFJEEGI_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.OOEMIBFNLLD> JCKNGFJEEGI {
      get { return jCKNGFJEEGI_; }
    }

    /// <summary>Field number for the "EBOOLGNACJJ" field.</summary>
    public const int EBOOLGNACJJFieldNumber = 3;
    private ulong eBOOLGNACJJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EBOOLGNACJJ {
      get { return eBOOLGNACJJ_; }
      set {
        eBOOLGNACJJ_ = value;
      }
    }

    /// <summary>Field number for the "DGEPMKFFOAB" field.</summary>
    public const int DGEPMKFFOABFieldNumber = 14;
    private uint dGEPMKFFOAB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DGEPMKFFOAB {
      get { return dGEPMKFFOAB_; }
      set {
        dGEPMKFFOAB_ = value;
      }
    }

    /// <summary>Field number for the "LJJMLEIOIFE" field.</summary>
    public const int LJJMLEIOIFEFieldNumber = 8;
    private uint lJJMLEIOIFE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LJJMLEIOIFE {
      get { return lJJMLEIOIFE_; }
      set {
        lJJMLEIOIFE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BCMOKFHJMPM);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BCMOKFHJMPM other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PoolId != other.PoolId) return false;
      if (BNOLDNBMJHF != other.BNOLDNBMJHF) return false;
      if (FHOLFDONOII != other.FHOLFDONOII) return false;
      if (DGALCMFIDFP != other.DGALCMFIDFP) return false;
      if (PJDFBPBMBBA != other.PJDFBPBMBBA) return false;
      if (OMGKJLJIHLH != other.OMGKJLJIHLH) return false;
      if (JOJNDGBEJEK != other.JOJNDGBEJEK) return false;
      if (JLEGPNIHMJD != other.JLEGPNIHMJD) return false;
      if(!eBABBEJIPJN_.Equals(other.eBABBEJIPJN_)) return false;
      if(!kGBEJKNCLFK_.Equals(other.kGBEJKNCLFK_)) return false;
      if (JGNIHLJFJPP != other.JGNIHLJFJPP) return false;
      if(!iFKFEPKHLGN_.Equals(other.iFKFEPKHLGN_)) return false;
      if (DDIBEFMILMP != other.DDIBEFMILMP) return false;
      if(!cJFMAIAKENL_.Equals(other.cJFMAIAKENL_)) return false;
      if(!jCKNGFJEEGI_.Equals(other.jCKNGFJEEGI_)) return false;
      if (EBOOLGNACJJ != other.EBOOLGNACJJ) return false;
      if (DGEPMKFFOAB != other.DGEPMKFFOAB) return false;
      if (LJJMLEIOIFE != other.LJJMLEIOIFE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PoolId != 0) hash ^= PoolId.GetHashCode();
      if (BNOLDNBMJHF != 0) hash ^= BNOLDNBMJHF.GetHashCode();
      if (FHOLFDONOII != false) hash ^= FHOLFDONOII.GetHashCode();
      if (DGALCMFIDFP != 0) hash ^= DGALCMFIDFP.GetHashCode();
      if (PJDFBPBMBBA.Length != 0) hash ^= PJDFBPBMBBA.GetHashCode();
      if (OMGKJLJIHLH != 0UL) hash ^= OMGKJLJIHLH.GetHashCode();
      if (JOJNDGBEJEK != 0UL) hash ^= JOJNDGBEJEK.GetHashCode();
      if (JLEGPNIHMJD.Length != 0) hash ^= JLEGPNIHMJD.GetHashCode();
      hash ^= eBABBEJIPJN_.GetHashCode();
      hash ^= kGBEJKNCLFK_.GetHashCode();
      if (JGNIHLJFJPP != 0) hash ^= JGNIHLJFJPP.GetHashCode();
      hash ^= iFKFEPKHLGN_.GetHashCode();
      if (DDIBEFMILMP.Length != 0) hash ^= DDIBEFMILMP.GetHashCode();
      hash ^= cJFMAIAKENL_.GetHashCode();
      hash ^= jCKNGFJEEGI_.GetHashCode();
      if (EBOOLGNACJJ != 0UL) hash ^= EBOOLGNACJJ.GetHashCode();
      if (DGEPMKFFOAB != 0) hash ^= DGEPMKFFOAB.GetHashCode();
      if (LJJMLEIOIFE != 0) hash ^= LJJMLEIOIFE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (JGNIHLJFJPP != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(JGNIHLJFJPP);
      }
      kGBEJKNCLFK_.WriteTo(output, _repeated_kGBEJKNCLFK_codec);
      if (EBOOLGNACJJ != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(EBOOLGNACJJ);
      }
      if (BNOLDNBMJHF != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BNOLDNBMJHF);
      }
      if (FHOLFDONOII != false) {
        output.WriteRawTag(40);
        output.WriteBool(FHOLFDONOII);
      }
      iFKFEPKHLGN_.WriteTo(output, _repeated_iFKFEPKHLGN_codec);
      eBABBEJIPJN_.WriteTo(output, _repeated_eBABBEJIPJN_codec);
      if (LJJMLEIOIFE != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(LJJMLEIOIFE);
      }
      if (PoolId != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(PoolId);
      }
      if (JOJNDGBEJEK != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(JOJNDGBEJEK);
      }
      cJFMAIAKENL_.WriteTo(output, _repeated_cJFMAIAKENL_codec);
      if (DGALCMFIDFP != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(DGALCMFIDFP);
      }
      if (OMGKJLJIHLH != 0UL) {
        output.WriteRawTag(104);
        output.WriteUInt64(OMGKJLJIHLH);
      }
      if (DGEPMKFFOAB != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(DGEPMKFFOAB);
      }
      jCKNGFJEEGI_.WriteTo(output, _repeated_jCKNGFJEEGI_codec);
      if (DDIBEFMILMP.Length != 0) {
        output.WriteRawTag(138, 4);
        output.WriteString(DDIBEFMILMP);
      }
      if (JLEGPNIHMJD.Length != 0) {
        output.WriteRawTag(194, 14);
        output.WriteString(JLEGPNIHMJD);
      }
      if (PJDFBPBMBBA.Length != 0) {
        output.WriteRawTag(146, 39);
        output.WriteString(PJDFBPBMBBA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (JGNIHLJFJPP != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(JGNIHLJFJPP);
      }
      kGBEJKNCLFK_.WriteTo(ref output, _repeated_kGBEJKNCLFK_codec);
      if (EBOOLGNACJJ != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(EBOOLGNACJJ);
      }
      if (BNOLDNBMJHF != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BNOLDNBMJHF);
      }
      if (FHOLFDONOII != false) {
        output.WriteRawTag(40);
        output.WriteBool(FHOLFDONOII);
      }
      iFKFEPKHLGN_.WriteTo(ref output, _repeated_iFKFEPKHLGN_codec);
      eBABBEJIPJN_.WriteTo(ref output, _repeated_eBABBEJIPJN_codec);
      if (LJJMLEIOIFE != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(LJJMLEIOIFE);
      }
      if (PoolId != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(PoolId);
      }
      if (JOJNDGBEJEK != 0UL) {
        output.WriteRawTag(80);
        output.WriteUInt64(JOJNDGBEJEK);
      }
      cJFMAIAKENL_.WriteTo(ref output, _repeated_cJFMAIAKENL_codec);
      if (DGALCMFIDFP != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(DGALCMFIDFP);
      }
      if (OMGKJLJIHLH != 0UL) {
        output.WriteRawTag(104);
        output.WriteUInt64(OMGKJLJIHLH);
      }
      if (DGEPMKFFOAB != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(DGEPMKFFOAB);
      }
      jCKNGFJEEGI_.WriteTo(ref output, _repeated_jCKNGFJEEGI_codec);
      if (DDIBEFMILMP.Length != 0) {
        output.WriteRawTag(138, 4);
        output.WriteString(DDIBEFMILMP);
      }
      if (JLEGPNIHMJD.Length != 0) {
        output.WriteRawTag(194, 14);
        output.WriteString(JLEGPNIHMJD);
      }
      if (PJDFBPBMBBA.Length != 0) {
        output.WriteRawTag(146, 39);
        output.WriteString(PJDFBPBMBBA);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PoolId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PoolId);
      }
      if (BNOLDNBMJHF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BNOLDNBMJHF);
      }
      if (FHOLFDONOII != false) {
        size += 1 + 1;
      }
      if (DGALCMFIDFP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DGALCMFIDFP);
      }
      if (PJDFBPBMBBA.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(PJDFBPBMBBA);
      }
      if (OMGKJLJIHLH != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(OMGKJLJIHLH);
      }
      if (JOJNDGBEJEK != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(JOJNDGBEJEK);
      }
      if (JLEGPNIHMJD.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(JLEGPNIHMJD);
      }
      size += eBABBEJIPJN_.CalculateSize(_repeated_eBABBEJIPJN_codec);
      size += kGBEJKNCLFK_.CalculateSize(_repeated_kGBEJKNCLFK_codec);
      if (JGNIHLJFJPP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JGNIHLJFJPP);
      }
      size += iFKFEPKHLGN_.CalculateSize(_repeated_iFKFEPKHLGN_codec);
      if (DDIBEFMILMP.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(DDIBEFMILMP);
      }
      size += cJFMAIAKENL_.CalculateSize(_repeated_cJFMAIAKENL_codec);
      size += jCKNGFJEEGI_.CalculateSize(_repeated_jCKNGFJEEGI_codec);
      if (EBOOLGNACJJ != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EBOOLGNACJJ);
      }
      if (DGEPMKFFOAB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DGEPMKFFOAB);
      }
      if (LJJMLEIOIFE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LJJMLEIOIFE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BCMOKFHJMPM other) {
      if (other == null) {
        return;
      }
      if (other.PoolId != 0) {
        PoolId = other.PoolId;
      }
      if (other.BNOLDNBMJHF != 0) {
        BNOLDNBMJHF = other.BNOLDNBMJHF;
      }
      if (other.FHOLFDONOII != false) {
        FHOLFDONOII = other.FHOLFDONOII;
      }
      if (other.DGALCMFIDFP != 0) {
        DGALCMFIDFP = other.DGALCMFIDFP;
      }
      if (other.PJDFBPBMBBA.Length != 0) {
        PJDFBPBMBBA = other.PJDFBPBMBBA;
      }
      if (other.OMGKJLJIHLH != 0UL) {
        OMGKJLJIHLH = other.OMGKJLJIHLH;
      }
      if (other.JOJNDGBEJEK != 0UL) {
        JOJNDGBEJEK = other.JOJNDGBEJEK;
      }
      if (other.JLEGPNIHMJD.Length != 0) {
        JLEGPNIHMJD = other.JLEGPNIHMJD;
      }
      eBABBEJIPJN_.Add(other.eBABBEJIPJN_);
      kGBEJKNCLFK_.Add(other.kGBEJKNCLFK_);
      if (other.JGNIHLJFJPP != 0) {
        JGNIHLJFJPP = other.JGNIHLJFJPP;
      }
      iFKFEPKHLGN_.Add(other.iFKFEPKHLGN_);
      if (other.DDIBEFMILMP.Length != 0) {
        DDIBEFMILMP = other.DDIBEFMILMP;
      }
      cJFMAIAKENL_.Add(other.cJFMAIAKENL_);
      jCKNGFJEEGI_.Add(other.jCKNGFJEEGI_);
      if (other.EBOOLGNACJJ != 0UL) {
        EBOOLGNACJJ = other.EBOOLGNACJJ;
      }
      if (other.DGEPMKFFOAB != 0) {
        DGEPMKFFOAB = other.DGEPMKFFOAB;
      }
      if (other.LJJMLEIOIFE != 0) {
        LJJMLEIOIFE = other.LJJMLEIOIFE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            JGNIHLJFJPP = input.ReadUInt32();
            break;
          }
          case 18: {
            kGBEJKNCLFK_.AddEntriesFrom(input, _repeated_kGBEJKNCLFK_codec);
            break;
          }
          case 24: {
            EBOOLGNACJJ = input.ReadUInt64();
            break;
          }
          case 32: {
            BNOLDNBMJHF = input.ReadUInt32();
            break;
          }
          case 40: {
            FHOLFDONOII = input.ReadBool();
            break;
          }
          case 50: {
            iFKFEPKHLGN_.AddEntriesFrom(input, _repeated_iFKFEPKHLGN_codec);
            break;
          }
          case 58: {
            eBABBEJIPJN_.AddEntriesFrom(input, _repeated_eBABBEJIPJN_codec);
            break;
          }
          case 64: {
            LJJMLEIOIFE = input.ReadUInt32();
            break;
          }
          case 72: {
            PoolId = input.ReadUInt32();
            break;
          }
          case 80: {
            JOJNDGBEJEK = input.ReadUInt64();
            break;
          }
          case 90: {
            cJFMAIAKENL_.AddEntriesFrom(input, _repeated_cJFMAIAKENL_codec);
            break;
          }
          case 96: {
            DGALCMFIDFP = input.ReadUInt32();
            break;
          }
          case 104: {
            OMGKJLJIHLH = input.ReadUInt64();
            break;
          }
          case 112: {
            DGEPMKFFOAB = input.ReadUInt32();
            break;
          }
          case 122: {
            jCKNGFJEEGI_.AddEntriesFrom(input, _repeated_jCKNGFJEEGI_codec);
            break;
          }
          case 522: {
            DDIBEFMILMP = input.ReadString();
            break;
          }
          case 1858: {
            JLEGPNIHMJD = input.ReadString();
            break;
          }
          case 5010: {
            PJDFBPBMBBA = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            JGNIHLJFJPP = input.ReadUInt32();
            break;
          }
          case 18: {
            kGBEJKNCLFK_.AddEntriesFrom(ref input, _repeated_kGBEJKNCLFK_codec);
            break;
          }
          case 24: {
            EBOOLGNACJJ = input.ReadUInt64();
            break;
          }
          case 32: {
            BNOLDNBMJHF = input.ReadUInt32();
            break;
          }
          case 40: {
            FHOLFDONOII = input.ReadBool();
            break;
          }
          case 50: {
            iFKFEPKHLGN_.AddEntriesFrom(ref input, _repeated_iFKFEPKHLGN_codec);
            break;
          }
          case 58: {
            eBABBEJIPJN_.AddEntriesFrom(ref input, _repeated_eBABBEJIPJN_codec);
            break;
          }
          case 64: {
            LJJMLEIOIFE = input.ReadUInt32();
            break;
          }
          case 72: {
            PoolId = input.ReadUInt32();
            break;
          }
          case 80: {
            JOJNDGBEJEK = input.ReadUInt64();
            break;
          }
          case 90: {
            cJFMAIAKENL_.AddEntriesFrom(ref input, _repeated_cJFMAIAKENL_codec);
            break;
          }
          case 96: {
            DGALCMFIDFP = input.ReadUInt32();
            break;
          }
          case 104: {
            OMGKJLJIHLH = input.ReadUInt64();
            break;
          }
          case 112: {
            DGEPMKFFOAB = input.ReadUInt32();
            break;
          }
          case 122: {
            jCKNGFJEEGI_.AddEntriesFrom(ref input, _repeated_jCKNGFJEEGI_codec);
            break;
          }
          case 522: {
            DDIBEFMILMP = input.ReadString();
            break;
          }
          case 1858: {
            JLEGPNIHMJD = input.ReadString();
            break;
          }
          case 5010: {
            PJDFBPBMBBA = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
