// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BLNEHDIFMOO.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from BLNEHDIFMOO.proto</summary>
  public static partial class BLNEHDIFMOOReflection {

    #region Descriptor
    /// <summary>File descriptor for BLNEHDIFMOO.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BLNEHDIFMOOReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFCTE5FSERJRk1PTy5wcm90bxocTXVzZXVtUmFuZG9tRXZlbnRTdGF0ZS5w",
            "cm90byKwAQoLQkxORUhESUZNT08SEAoIZXZlbnRfaWQYDCABKA0SEwoLQ09H",
            "QkNQTE1ORkQYBSABKA0SEwoLSENBR0xDTEVKTkQYByABKA0SEwoLREdKQkFD",
            "QklJQ08YBCABKA0SJgoFc3RhdGUYDiABKA4yFy5NdXNldW1SYW5kb21FdmVu",
            "dFN0YXRlEhMKC0hBQUJFRktIQU1JGAogAygNEhMKC0JNQkdLTEtFQ0FKGAYg",
            "ASgNQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.MuseumRandomEventStateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.BLNEHDIFMOO), global::EggLink.DanhengServer.Proto.BLNEHDIFMOO.Parser, new[]{ "EventId", "COGBCPLMNFD", "HCAGLCLEJND", "DGJBACBIICO", "State", "HAABEFKHAMI", "BMBGKLKECAJ" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BLNEHDIFMOO : pb::IMessage<BLNEHDIFMOO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BLNEHDIFMOO> _parser = new pb::MessageParser<BLNEHDIFMOO>(() => new BLNEHDIFMOO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BLNEHDIFMOO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.BLNEHDIFMOOReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BLNEHDIFMOO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BLNEHDIFMOO(BLNEHDIFMOO other) : this() {
      eventId_ = other.eventId_;
      cOGBCPLMNFD_ = other.cOGBCPLMNFD_;
      hCAGLCLEJND_ = other.hCAGLCLEJND_;
      dGJBACBIICO_ = other.dGJBACBIICO_;
      state_ = other.state_;
      hAABEFKHAMI_ = other.hAABEFKHAMI_.Clone();
      bMBGKLKECAJ_ = other.bMBGKLKECAJ_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BLNEHDIFMOO Clone() {
      return new BLNEHDIFMOO(this);
    }

    /// <summary>Field number for the "event_id" field.</summary>
    public const int EventIdFieldNumber = 12;
    private uint eventId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }

    /// <summary>Field number for the "COGBCPLMNFD" field.</summary>
    public const int COGBCPLMNFDFieldNumber = 5;
    private uint cOGBCPLMNFD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint COGBCPLMNFD {
      get { return cOGBCPLMNFD_; }
      set {
        cOGBCPLMNFD_ = value;
      }
    }

    /// <summary>Field number for the "HCAGLCLEJND" field.</summary>
    public const int HCAGLCLEJNDFieldNumber = 7;
    private uint hCAGLCLEJND_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HCAGLCLEJND {
      get { return hCAGLCLEJND_; }
      set {
        hCAGLCLEJND_ = value;
      }
    }

    /// <summary>Field number for the "DGJBACBIICO" field.</summary>
    public const int DGJBACBIICOFieldNumber = 4;
    private uint dGJBACBIICO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DGJBACBIICO {
      get { return dGJBACBIICO_; }
      set {
        dGJBACBIICO_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 14;
    private global::EggLink.DanhengServer.Proto.MuseumRandomEventState state_ = global::EggLink.DanhengServer.Proto.MuseumRandomEventState.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.MuseumRandomEventState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "HAABEFKHAMI" field.</summary>
    public const int HAABEFKHAMIFieldNumber = 10;
    private static readonly pb::FieldCodec<uint> _repeated_hAABEFKHAMI_codec
        = pb::FieldCodec.ForUInt32(82);
    private readonly pbc::RepeatedField<uint> hAABEFKHAMI_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> HAABEFKHAMI {
      get { return hAABEFKHAMI_; }
    }

    /// <summary>Field number for the "BMBGKLKECAJ" field.</summary>
    public const int BMBGKLKECAJFieldNumber = 6;
    private uint bMBGKLKECAJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BMBGKLKECAJ {
      get { return bMBGKLKECAJ_; }
      set {
        bMBGKLKECAJ_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BLNEHDIFMOO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BLNEHDIFMOO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventId != other.EventId) return false;
      if (COGBCPLMNFD != other.COGBCPLMNFD) return false;
      if (HCAGLCLEJND != other.HCAGLCLEJND) return false;
      if (DGJBACBIICO != other.DGJBACBIICO) return false;
      if (State != other.State) return false;
      if(!hAABEFKHAMI_.Equals(other.hAABEFKHAMI_)) return false;
      if (BMBGKLKECAJ != other.BMBGKLKECAJ) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventId != 0) hash ^= EventId.GetHashCode();
      if (COGBCPLMNFD != 0) hash ^= COGBCPLMNFD.GetHashCode();
      if (HCAGLCLEJND != 0) hash ^= HCAGLCLEJND.GetHashCode();
      if (DGJBACBIICO != 0) hash ^= DGJBACBIICO.GetHashCode();
      if (State != global::EggLink.DanhengServer.Proto.MuseumRandomEventState.None) hash ^= State.GetHashCode();
      hash ^= hAABEFKHAMI_.GetHashCode();
      if (BMBGKLKECAJ != 0) hash ^= BMBGKLKECAJ.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DGJBACBIICO != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(DGJBACBIICO);
      }
      if (COGBCPLMNFD != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(COGBCPLMNFD);
      }
      if (BMBGKLKECAJ != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BMBGKLKECAJ);
      }
      if (HCAGLCLEJND != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HCAGLCLEJND);
      }
      hAABEFKHAMI_.WriteTo(output, _repeated_hAABEFKHAMI_codec);
      if (EventId != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(EventId);
      }
      if (State != global::EggLink.DanhengServer.Proto.MuseumRandomEventState.None) {
        output.WriteRawTag(112);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DGJBACBIICO != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(DGJBACBIICO);
      }
      if (COGBCPLMNFD != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(COGBCPLMNFD);
      }
      if (BMBGKLKECAJ != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(BMBGKLKECAJ);
      }
      if (HCAGLCLEJND != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(HCAGLCLEJND);
      }
      hAABEFKHAMI_.WriteTo(ref output, _repeated_hAABEFKHAMI_codec);
      if (EventId != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(EventId);
      }
      if (State != global::EggLink.DanhengServer.Proto.MuseumRandomEventState.None) {
        output.WriteRawTag(112);
        output.WriteEnum((int) State);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EventId);
      }
      if (COGBCPLMNFD != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(COGBCPLMNFD);
      }
      if (HCAGLCLEJND != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HCAGLCLEJND);
      }
      if (DGJBACBIICO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DGJBACBIICO);
      }
      if (State != global::EggLink.DanhengServer.Proto.MuseumRandomEventState.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      size += hAABEFKHAMI_.CalculateSize(_repeated_hAABEFKHAMI_codec);
      if (BMBGKLKECAJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BMBGKLKECAJ);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BLNEHDIFMOO other) {
      if (other == null) {
        return;
      }
      if (other.EventId != 0) {
        EventId = other.EventId;
      }
      if (other.COGBCPLMNFD != 0) {
        COGBCPLMNFD = other.COGBCPLMNFD;
      }
      if (other.HCAGLCLEJND != 0) {
        HCAGLCLEJND = other.HCAGLCLEJND;
      }
      if (other.DGJBACBIICO != 0) {
        DGJBACBIICO = other.DGJBACBIICO;
      }
      if (other.State != global::EggLink.DanhengServer.Proto.MuseumRandomEventState.None) {
        State = other.State;
      }
      hAABEFKHAMI_.Add(other.hAABEFKHAMI_);
      if (other.BMBGKLKECAJ != 0) {
        BMBGKLKECAJ = other.BMBGKLKECAJ;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 32: {
            DGJBACBIICO = input.ReadUInt32();
            break;
          }
          case 40: {
            COGBCPLMNFD = input.ReadUInt32();
            break;
          }
          case 48: {
            BMBGKLKECAJ = input.ReadUInt32();
            break;
          }
          case 56: {
            HCAGLCLEJND = input.ReadUInt32();
            break;
          }
          case 82:
          case 80: {
            hAABEFKHAMI_.AddEntriesFrom(input, _repeated_hAABEFKHAMI_codec);
            break;
          }
          case 96: {
            EventId = input.ReadUInt32();
            break;
          }
          case 112: {
            State = (global::EggLink.DanhengServer.Proto.MuseumRandomEventState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 32: {
            DGJBACBIICO = input.ReadUInt32();
            break;
          }
          case 40: {
            COGBCPLMNFD = input.ReadUInt32();
            break;
          }
          case 48: {
            BMBGKLKECAJ = input.ReadUInt32();
            break;
          }
          case 56: {
            HCAGLCLEJND = input.ReadUInt32();
            break;
          }
          case 82:
          case 80: {
            hAABEFKHAMI_.AddEntriesFrom(ref input, _repeated_hAABEFKHAMI_codec);
            break;
          }
          case 96: {
            EventId = input.ReadUInt32();
            break;
          }
          case 112: {
            State = (global::EggLink.DanhengServer.Proto.MuseumRandomEventState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
