// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChessRogueQueryInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChessRogueQueryInfo.proto</summary>
  public static partial class ChessRogueQueryInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for ChessRogueQueryInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChessRogueQueryInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlDaGVzc1JvZ3VlUXVlcnlJbmZvLnByb3RvGiJDaGVzc1JvZ3VlUXVlcnlE",
            "aWZmY3VsdHlJbmZvLnByb3RvGh1DaGVzc1JvZ3VlUXVlcnlEaWNlSW5mby5w",
            "cm90bxoaQ2hlc3NSb2d1ZVRhbGVudEluZm8ucHJvdG8aHUNoZXNzUm9ndWVR",
            "dWVyeUFlb25JbmZvLnByb3RvIp8CChNDaGVzc1JvZ3VlUXVlcnlJbmZvEjEK",
            "D3F1ZXJ5X2RpY2VfaW5mbxgIIAEoCzIYLkNoZXNzUm9ndWVRdWVyeURpY2VJ",
            "bmZvEjwKFXJvZ3VlX2RpZmZpY3VsdHlfaW5mbxgCIAEoCzIdLkNoZXNzUm9n",
            "dWVRdWVyeURpZmZjdWx0eUluZm8SMQoPY2hlc3NfYWVvbl9pbmZvGAYgASgL",
            "MhguQ2hlc3NSb2d1ZVF1ZXJ5QWVvbkluZm8SFAoMYXJlYV9pZF9saXN0GAsg",
            "AygNEi8KEHRhbGVudF9pbmZvX2xpc3QYBCABKAsyFS5DaGVzc1JvZ3VlVGFs",
            "ZW50SW5mbxIdChVleHBsb3JlZF9hcmVhX2lkX2xpc3QYDSADKA1CHqoCG0Vn",
            "Z0xpbmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.ChessRogueQueryDiffcultyInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.ChessRogueQueryDiceInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.ChessRogueTalentInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.ChessRogueQueryAeonInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ChessRogueQueryInfo), global::EggLink.DanhengServer.Proto.ChessRogueQueryInfo.Parser, new[]{ "QueryDiceInfo", "RogueDifficultyInfo", "ChessAeonInfo", "AreaIdList", "TalentInfoList", "ExploredAreaIdList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChessRogueQueryInfo : pb::IMessage<ChessRogueQueryInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChessRogueQueryInfo> _parser = new pb::MessageParser<ChessRogueQueryInfo>(() => new ChessRogueQueryInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChessRogueQueryInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ChessRogueQueryInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueQueryInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueQueryInfo(ChessRogueQueryInfo other) : this() {
      queryDiceInfo_ = other.queryDiceInfo_ != null ? other.queryDiceInfo_.Clone() : null;
      rogueDifficultyInfo_ = other.rogueDifficultyInfo_ != null ? other.rogueDifficultyInfo_.Clone() : null;
      chessAeonInfo_ = other.chessAeonInfo_ != null ? other.chessAeonInfo_.Clone() : null;
      areaIdList_ = other.areaIdList_.Clone();
      talentInfoList_ = other.talentInfoList_ != null ? other.talentInfoList_.Clone() : null;
      exploredAreaIdList_ = other.exploredAreaIdList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChessRogueQueryInfo Clone() {
      return new ChessRogueQueryInfo(this);
    }

    /// <summary>Field number for the "query_dice_info" field.</summary>
    public const int QueryDiceInfoFieldNumber = 8;
    private global::EggLink.DanhengServer.Proto.ChessRogueQueryDiceInfo queryDiceInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueQueryDiceInfo QueryDiceInfo {
      get { return queryDiceInfo_; }
      set {
        queryDiceInfo_ = value;
      }
    }

    /// <summary>Field number for the "rogue_difficulty_info" field.</summary>
    public const int RogueDifficultyInfoFieldNumber = 2;
    private global::EggLink.DanhengServer.Proto.ChessRogueQueryDiffcultyInfo rogueDifficultyInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueQueryDiffcultyInfo RogueDifficultyInfo {
      get { return rogueDifficultyInfo_; }
      set {
        rogueDifficultyInfo_ = value;
      }
    }

    /// <summary>Field number for the "chess_aeon_info" field.</summary>
    public const int ChessAeonInfoFieldNumber = 6;
    private global::EggLink.DanhengServer.Proto.ChessRogueQueryAeonInfo chessAeonInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueQueryAeonInfo ChessAeonInfo {
      get { return chessAeonInfo_; }
      set {
        chessAeonInfo_ = value;
      }
    }

    /// <summary>Field number for the "area_id_list" field.</summary>
    public const int AreaIdListFieldNumber = 11;
    private static readonly pb::FieldCodec<uint> _repeated_areaIdList_codec
        = pb::FieldCodec.ForUInt32(90);
    private readonly pbc::RepeatedField<uint> areaIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> AreaIdList {
      get { return areaIdList_; }
    }

    /// <summary>Field number for the "talent_info_list" field.</summary>
    public const int TalentInfoListFieldNumber = 4;
    private global::EggLink.DanhengServer.Proto.ChessRogueTalentInfo talentInfoList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.ChessRogueTalentInfo TalentInfoList {
      get { return talentInfoList_; }
      set {
        talentInfoList_ = value;
      }
    }

    /// <summary>Field number for the "explored_area_id_list" field.</summary>
    public const int ExploredAreaIdListFieldNumber = 13;
    private static readonly pb::FieldCodec<uint> _repeated_exploredAreaIdList_codec
        = pb::FieldCodec.ForUInt32(106);
    private readonly pbc::RepeatedField<uint> exploredAreaIdList_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> ExploredAreaIdList {
      get { return exploredAreaIdList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChessRogueQueryInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChessRogueQueryInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(QueryDiceInfo, other.QueryDiceInfo)) return false;
      if (!object.Equals(RogueDifficultyInfo, other.RogueDifficultyInfo)) return false;
      if (!object.Equals(ChessAeonInfo, other.ChessAeonInfo)) return false;
      if(!areaIdList_.Equals(other.areaIdList_)) return false;
      if (!object.Equals(TalentInfoList, other.TalentInfoList)) return false;
      if(!exploredAreaIdList_.Equals(other.exploredAreaIdList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (queryDiceInfo_ != null) hash ^= QueryDiceInfo.GetHashCode();
      if (rogueDifficultyInfo_ != null) hash ^= RogueDifficultyInfo.GetHashCode();
      if (chessAeonInfo_ != null) hash ^= ChessAeonInfo.GetHashCode();
      hash ^= areaIdList_.GetHashCode();
      if (talentInfoList_ != null) hash ^= TalentInfoList.GetHashCode();
      hash ^= exploredAreaIdList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (rogueDifficultyInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RogueDifficultyInfo);
      }
      if (talentInfoList_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TalentInfoList);
      }
      if (chessAeonInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ChessAeonInfo);
      }
      if (queryDiceInfo_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(QueryDiceInfo);
      }
      areaIdList_.WriteTo(output, _repeated_areaIdList_codec);
      exploredAreaIdList_.WriteTo(output, _repeated_exploredAreaIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (rogueDifficultyInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RogueDifficultyInfo);
      }
      if (talentInfoList_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TalentInfoList);
      }
      if (chessAeonInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ChessAeonInfo);
      }
      if (queryDiceInfo_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(QueryDiceInfo);
      }
      areaIdList_.WriteTo(ref output, _repeated_areaIdList_codec);
      exploredAreaIdList_.WriteTo(ref output, _repeated_exploredAreaIdList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (queryDiceInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(QueryDiceInfo);
      }
      if (rogueDifficultyInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RogueDifficultyInfo);
      }
      if (chessAeonInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChessAeonInfo);
      }
      size += areaIdList_.CalculateSize(_repeated_areaIdList_codec);
      if (talentInfoList_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TalentInfoList);
      }
      size += exploredAreaIdList_.CalculateSize(_repeated_exploredAreaIdList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChessRogueQueryInfo other) {
      if (other == null) {
        return;
      }
      if (other.queryDiceInfo_ != null) {
        if (queryDiceInfo_ == null) {
          QueryDiceInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryDiceInfo();
        }
        QueryDiceInfo.MergeFrom(other.QueryDiceInfo);
      }
      if (other.rogueDifficultyInfo_ != null) {
        if (rogueDifficultyInfo_ == null) {
          RogueDifficultyInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryDiffcultyInfo();
        }
        RogueDifficultyInfo.MergeFrom(other.RogueDifficultyInfo);
      }
      if (other.chessAeonInfo_ != null) {
        if (chessAeonInfo_ == null) {
          ChessAeonInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryAeonInfo();
        }
        ChessAeonInfo.MergeFrom(other.ChessAeonInfo);
      }
      areaIdList_.Add(other.areaIdList_);
      if (other.talentInfoList_ != null) {
        if (talentInfoList_ == null) {
          TalentInfoList = new global::EggLink.DanhengServer.Proto.ChessRogueTalentInfo();
        }
        TalentInfoList.MergeFrom(other.TalentInfoList);
      }
      exploredAreaIdList_.Add(other.exploredAreaIdList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (rogueDifficultyInfo_ == null) {
              RogueDifficultyInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryDiffcultyInfo();
            }
            input.ReadMessage(RogueDifficultyInfo);
            break;
          }
          case 34: {
            if (talentInfoList_ == null) {
              TalentInfoList = new global::EggLink.DanhengServer.Proto.ChessRogueTalentInfo();
            }
            input.ReadMessage(TalentInfoList);
            break;
          }
          case 50: {
            if (chessAeonInfo_ == null) {
              ChessAeonInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryAeonInfo();
            }
            input.ReadMessage(ChessAeonInfo);
            break;
          }
          case 66: {
            if (queryDiceInfo_ == null) {
              QueryDiceInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryDiceInfo();
            }
            input.ReadMessage(QueryDiceInfo);
            break;
          }
          case 90:
          case 88: {
            areaIdList_.AddEntriesFrom(input, _repeated_areaIdList_codec);
            break;
          }
          case 106:
          case 104: {
            exploredAreaIdList_.AddEntriesFrom(input, _repeated_exploredAreaIdList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (rogueDifficultyInfo_ == null) {
              RogueDifficultyInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryDiffcultyInfo();
            }
            input.ReadMessage(RogueDifficultyInfo);
            break;
          }
          case 34: {
            if (talentInfoList_ == null) {
              TalentInfoList = new global::EggLink.DanhengServer.Proto.ChessRogueTalentInfo();
            }
            input.ReadMessage(TalentInfoList);
            break;
          }
          case 50: {
            if (chessAeonInfo_ == null) {
              ChessAeonInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryAeonInfo();
            }
            input.ReadMessage(ChessAeonInfo);
            break;
          }
          case 66: {
            if (queryDiceInfo_ == null) {
              QueryDiceInfo = new global::EggLink.DanhengServer.Proto.ChessRogueQueryDiceInfo();
            }
            input.ReadMessage(QueryDiceInfo);
            break;
          }
          case 90:
          case 88: {
            areaIdList_.AddEntriesFrom(ref input, _repeated_areaIdList_codec);
            break;
          }
          case 106:
          case 104: {
            exploredAreaIdList_.AddEntriesFrom(ref input, _repeated_exploredAreaIdList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
