// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ChimeraRoundWorkStartCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from ChimeraRoundWorkStartCsReq.proto</summary>
  public static partial class ChimeraRoundWorkStartCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for ChimeraRoundWorkStartCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChimeraRoundWorkStartCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBDaGltZXJhUm91bmRXb3JrU3RhcnRDc1JlcS5wcm90bxoRSk1BQU5NUEFO",
            "SE0ucHJvdG8aEU1QSkRJQkNDT0hGLnByb3RvIocBChpDaGltZXJhUm91bmRX",
            "b3JrU3RhcnRDc1JlcRIhCgtPUEFNQUVJSkNPSBgGIAMoCzIMLkpNQUFOTVBB",
            "TkhNEhwKBmxpbmV1cBgNIAEoCzIMLk1QSkRJQkNDT0hGEhMKC01ERkVFS0lL",
            "Qk1KGAkgASgNEhMKC0ZMR0pQSEVPUEFBGAwgASgNQh6qAhtFZ2dMaW5rLkRh",
            "bmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.JMAANMPANHMReflection.Descriptor, global::EggLink.DanhengServer.Proto.MPJDIBCCOHFReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.ChimeraRoundWorkStartCsReq), global::EggLink.DanhengServer.Proto.ChimeraRoundWorkStartCsReq.Parser, new[]{ "OPAMAEIJCOH", "Lineup", "MDFEEKIKBMJ", "FLGJPHEOPAA" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChimeraRoundWorkStartCsReq : pb::IMessage<ChimeraRoundWorkStartCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChimeraRoundWorkStartCsReq> _parser = new pb::MessageParser<ChimeraRoundWorkStartCsReq>(() => new ChimeraRoundWorkStartCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChimeraRoundWorkStartCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.ChimeraRoundWorkStartCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChimeraRoundWorkStartCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChimeraRoundWorkStartCsReq(ChimeraRoundWorkStartCsReq other) : this() {
      oPAMAEIJCOH_ = other.oPAMAEIJCOH_.Clone();
      lineup_ = other.lineup_ != null ? other.lineup_.Clone() : null;
      mDFEEKIKBMJ_ = other.mDFEEKIKBMJ_;
      fLGJPHEOPAA_ = other.fLGJPHEOPAA_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChimeraRoundWorkStartCsReq Clone() {
      return new ChimeraRoundWorkStartCsReq(this);
    }

    /// <summary>Field number for the "OPAMAEIJCOH" field.</summary>
    public const int OPAMAEIJCOHFieldNumber = 6;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.JMAANMPANHM> _repeated_oPAMAEIJCOH_codec
        = pb::FieldCodec.ForMessage(50, global::EggLink.DanhengServer.Proto.JMAANMPANHM.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JMAANMPANHM> oPAMAEIJCOH_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JMAANMPANHM>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JMAANMPANHM> OPAMAEIJCOH {
      get { return oPAMAEIJCOH_; }
    }

    /// <summary>Field number for the "lineup" field.</summary>
    public const int LineupFieldNumber = 13;
    private global::EggLink.DanhengServer.Proto.MPJDIBCCOHF lineup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.MPJDIBCCOHF Lineup {
      get { return lineup_; }
      set {
        lineup_ = value;
      }
    }

    /// <summary>Field number for the "MDFEEKIKBMJ" field.</summary>
    public const int MDFEEKIKBMJFieldNumber = 9;
    private uint mDFEEKIKBMJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MDFEEKIKBMJ {
      get { return mDFEEKIKBMJ_; }
      set {
        mDFEEKIKBMJ_ = value;
      }
    }

    /// <summary>Field number for the "FLGJPHEOPAA" field.</summary>
    public const int FLGJPHEOPAAFieldNumber = 12;
    private uint fLGJPHEOPAA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FLGJPHEOPAA {
      get { return fLGJPHEOPAA_; }
      set {
        fLGJPHEOPAA_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChimeraRoundWorkStartCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChimeraRoundWorkStartCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!oPAMAEIJCOH_.Equals(other.oPAMAEIJCOH_)) return false;
      if (!object.Equals(Lineup, other.Lineup)) return false;
      if (MDFEEKIKBMJ != other.MDFEEKIKBMJ) return false;
      if (FLGJPHEOPAA != other.FLGJPHEOPAA) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= oPAMAEIJCOH_.GetHashCode();
      if (lineup_ != null) hash ^= Lineup.GetHashCode();
      if (MDFEEKIKBMJ != 0) hash ^= MDFEEKIKBMJ.GetHashCode();
      if (FLGJPHEOPAA != 0) hash ^= FLGJPHEOPAA.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      oPAMAEIJCOH_.WriteTo(output, _repeated_oPAMAEIJCOH_codec);
      if (MDFEEKIKBMJ != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(MDFEEKIKBMJ);
      }
      if (FLGJPHEOPAA != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(FLGJPHEOPAA);
      }
      if (lineup_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Lineup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      oPAMAEIJCOH_.WriteTo(ref output, _repeated_oPAMAEIJCOH_codec);
      if (MDFEEKIKBMJ != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(MDFEEKIKBMJ);
      }
      if (FLGJPHEOPAA != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(FLGJPHEOPAA);
      }
      if (lineup_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(Lineup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += oPAMAEIJCOH_.CalculateSize(_repeated_oPAMAEIJCOH_codec);
      if (lineup_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Lineup);
      }
      if (MDFEEKIKBMJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MDFEEKIKBMJ);
      }
      if (FLGJPHEOPAA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FLGJPHEOPAA);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChimeraRoundWorkStartCsReq other) {
      if (other == null) {
        return;
      }
      oPAMAEIJCOH_.Add(other.oPAMAEIJCOH_);
      if (other.lineup_ != null) {
        if (lineup_ == null) {
          Lineup = new global::EggLink.DanhengServer.Proto.MPJDIBCCOHF();
        }
        Lineup.MergeFrom(other.Lineup);
      }
      if (other.MDFEEKIKBMJ != 0) {
        MDFEEKIKBMJ = other.MDFEEKIKBMJ;
      }
      if (other.FLGJPHEOPAA != 0) {
        FLGJPHEOPAA = other.FLGJPHEOPAA;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 50: {
            oPAMAEIJCOH_.AddEntriesFrom(input, _repeated_oPAMAEIJCOH_codec);
            break;
          }
          case 72: {
            MDFEEKIKBMJ = input.ReadUInt32();
            break;
          }
          case 96: {
            FLGJPHEOPAA = input.ReadUInt32();
            break;
          }
          case 106: {
            if (lineup_ == null) {
              Lineup = new global::EggLink.DanhengServer.Proto.MPJDIBCCOHF();
            }
            input.ReadMessage(Lineup);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 50: {
            oPAMAEIJCOH_.AddEntriesFrom(ref input, _repeated_oPAMAEIJCOH_codec);
            break;
          }
          case 72: {
            MDFEEKIKBMJ = input.ReadUInt32();
            break;
          }
          case 96: {
            FLGJPHEOPAA = input.ReadUInt32();
            break;
          }
          case 106: {
            if (lineup_ == null) {
              Lineup = new global::EggLink.DanhengServer.Proto.MPJDIBCCOHF();
            }
            input.ReadMessage(Lineup);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
