// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DMJLKIFEMMN.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from DMJLKIFEMMN.proto</summary>
  public static partial class DMJLKIFEMMNReflection {

    #region Descriptor
    /// <summary>File descriptor for DMJLKIFEMMN.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DMJLKIFEMMNReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFETUpMS0lGRU1NTi5wcm90bxoRUEJNS0tJQ01MREEucHJvdG8aEUtMSU5Q",
            "Qk5LSUlBLnByb3RvInwKC0RNSkxLSUZFTU1OEiMKC0dBSUJISkhET0hCGAkg",
            "ASgLMgwuS0xJTlBCTktJSUFIABIjCgtLUEpBRkJDUEVHSRgBIAEoCzIMLlBC",
            "TUtLSUNNTERBSAASFAoLSUdITEFCR0dJSkUYiQIgASgNQg0KC0FFQ0ZKRkdL",
            "S0FIQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.PBMKKICMLDAReflection.Descriptor, global::EggLink.DanhengServer.Proto.KLINPBNKIIAReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.DMJLKIFEMMN), global::EggLink.DanhengServer.Proto.DMJLKIFEMMN.Parser, new[]{ "GAIBHJHDOHB", "KPJAFBCPEGI", "IGHLABGGIJE" }, new[]{ "AECFJFGKKAH" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DMJLKIFEMMN : pb::IMessage<DMJLKIFEMMN>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DMJLKIFEMMN> _parser = new pb::MessageParser<DMJLKIFEMMN>(() => new DMJLKIFEMMN());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DMJLKIFEMMN> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.DMJLKIFEMMNReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DMJLKIFEMMN() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DMJLKIFEMMN(DMJLKIFEMMN other) : this() {
      iGHLABGGIJE_ = other.iGHLABGGIJE_;
      switch (other.AECFJFGKKAHCase) {
        case AECFJFGKKAHOneofCase.GAIBHJHDOHB:
          GAIBHJHDOHB = other.GAIBHJHDOHB.Clone();
          break;
        case AECFJFGKKAHOneofCase.KPJAFBCPEGI:
          KPJAFBCPEGI = other.KPJAFBCPEGI.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DMJLKIFEMMN Clone() {
      return new DMJLKIFEMMN(this);
    }

    /// <summary>Field number for the "GAIBHJHDOHB" field.</summary>
    public const int GAIBHJHDOHBFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.KLINPBNKIIA GAIBHJHDOHB {
      get { return aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB ? (global::EggLink.DanhengServer.Proto.KLINPBNKIIA) aECFJFGKKAH_ : null; }
      set {
        aECFJFGKKAH_ = value;
        aECFJFGKKAHCase_ = value == null ? AECFJFGKKAHOneofCase.None : AECFJFGKKAHOneofCase.GAIBHJHDOHB;
      }
    }

    /// <summary>Field number for the "KPJAFBCPEGI" field.</summary>
    public const int KPJAFBCPEGIFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PBMKKICMLDA KPJAFBCPEGI {
      get { return aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI ? (global::EggLink.DanhengServer.Proto.PBMKKICMLDA) aECFJFGKKAH_ : null; }
      set {
        aECFJFGKKAH_ = value;
        aECFJFGKKAHCase_ = value == null ? AECFJFGKKAHOneofCase.None : AECFJFGKKAHOneofCase.KPJAFBCPEGI;
      }
    }

    /// <summary>Field number for the "IGHLABGGIJE" field.</summary>
    public const int IGHLABGGIJEFieldNumber = 265;
    private uint iGHLABGGIJE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IGHLABGGIJE {
      get { return iGHLABGGIJE_; }
      set {
        iGHLABGGIJE_ = value;
      }
    }

    private object aECFJFGKKAH_;
    /// <summary>Enum of possible cases for the "AECFJFGKKAH" oneof.</summary>
    public enum AECFJFGKKAHOneofCase {
      None = 0,
      GAIBHJHDOHB = 9,
      KPJAFBCPEGI = 1,
    }
    private AECFJFGKKAHOneofCase aECFJFGKKAHCase_ = AECFJFGKKAHOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AECFJFGKKAHOneofCase AECFJFGKKAHCase {
      get { return aECFJFGKKAHCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAECFJFGKKAH() {
      aECFJFGKKAHCase_ = AECFJFGKKAHOneofCase.None;
      aECFJFGKKAH_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DMJLKIFEMMN);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DMJLKIFEMMN other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GAIBHJHDOHB, other.GAIBHJHDOHB)) return false;
      if (!object.Equals(KPJAFBCPEGI, other.KPJAFBCPEGI)) return false;
      if (IGHLABGGIJE != other.IGHLABGGIJE) return false;
      if (AECFJFGKKAHCase != other.AECFJFGKKAHCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB) hash ^= GAIBHJHDOHB.GetHashCode();
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI) hash ^= KPJAFBCPEGI.GetHashCode();
      if (IGHLABGGIJE != 0) hash ^= IGHLABGGIJE.GetHashCode();
      hash ^= (int) aECFJFGKKAHCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI) {
        output.WriteRawTag(10);
        output.WriteMessage(KPJAFBCPEGI);
      }
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB) {
        output.WriteRawTag(74);
        output.WriteMessage(GAIBHJHDOHB);
      }
      if (IGHLABGGIJE != 0) {
        output.WriteRawTag(200, 16);
        output.WriteUInt32(IGHLABGGIJE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI) {
        output.WriteRawTag(10);
        output.WriteMessage(KPJAFBCPEGI);
      }
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB) {
        output.WriteRawTag(74);
        output.WriteMessage(GAIBHJHDOHB);
      }
      if (IGHLABGGIJE != 0) {
        output.WriteRawTag(200, 16);
        output.WriteUInt32(IGHLABGGIJE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GAIBHJHDOHB);
      }
      if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KPJAFBCPEGI);
      }
      if (IGHLABGGIJE != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(IGHLABGGIJE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DMJLKIFEMMN other) {
      if (other == null) {
        return;
      }
      if (other.IGHLABGGIJE != 0) {
        IGHLABGGIJE = other.IGHLABGGIJE;
      }
      switch (other.AECFJFGKKAHCase) {
        case AECFJFGKKAHOneofCase.GAIBHJHDOHB:
          if (GAIBHJHDOHB == null) {
            GAIBHJHDOHB = new global::EggLink.DanhengServer.Proto.KLINPBNKIIA();
          }
          GAIBHJHDOHB.MergeFrom(other.GAIBHJHDOHB);
          break;
        case AECFJFGKKAHOneofCase.KPJAFBCPEGI:
          if (KPJAFBCPEGI == null) {
            KPJAFBCPEGI = new global::EggLink.DanhengServer.Proto.PBMKKICMLDA();
          }
          KPJAFBCPEGI.MergeFrom(other.KPJAFBCPEGI);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::EggLink.DanhengServer.Proto.PBMKKICMLDA subBuilder = new global::EggLink.DanhengServer.Proto.PBMKKICMLDA();
            if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI) {
              subBuilder.MergeFrom(KPJAFBCPEGI);
            }
            input.ReadMessage(subBuilder);
            KPJAFBCPEGI = subBuilder;
            break;
          }
          case 74: {
            global::EggLink.DanhengServer.Proto.KLINPBNKIIA subBuilder = new global::EggLink.DanhengServer.Proto.KLINPBNKIIA();
            if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB) {
              subBuilder.MergeFrom(GAIBHJHDOHB);
            }
            input.ReadMessage(subBuilder);
            GAIBHJHDOHB = subBuilder;
            break;
          }
          case 2120: {
            IGHLABGGIJE = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::EggLink.DanhengServer.Proto.PBMKKICMLDA subBuilder = new global::EggLink.DanhengServer.Proto.PBMKKICMLDA();
            if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.KPJAFBCPEGI) {
              subBuilder.MergeFrom(KPJAFBCPEGI);
            }
            input.ReadMessage(subBuilder);
            KPJAFBCPEGI = subBuilder;
            break;
          }
          case 74: {
            global::EggLink.DanhengServer.Proto.KLINPBNKIIA subBuilder = new global::EggLink.DanhengServer.Proto.KLINPBNKIIA();
            if (aECFJFGKKAHCase_ == AECFJFGKKAHOneofCase.GAIBHJHDOHB) {
              subBuilder.MergeFrom(GAIBHJHDOHB);
            }
            input.ReadMessage(subBuilder);
            GAIBHJHDOHB = subBuilder;
            break;
          }
          case 2120: {
            IGHLABGGIJE = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
