// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DoGachaScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from DoGachaScRsp.proto</summary>
  public static partial class DoGachaScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for DoGachaScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DoGachaScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJEb0dhY2hhU2NSc3AucHJvdG8aD0dhY2hhSXRlbS5wcm90byLSAQoMRG9H",
            "YWNoYVNjUnNwEhMKC1BFTklMSEdMSEhNGAkgASgNEiMKD2dhY2hhX2l0ZW1f",
            "bGlzdBgPIAMoCzIKLkdhY2hhSXRlbRITCgtHRElGQUFISUZCSBgLIAEoDRIR",
            "CglnYWNoYV9udW0YDSABKA0SEAoIZ2FjaGFfaWQYCCABKA0SDwoHcmV0Y29k",
            "ZRgOIAEoDRITCgtjZWlsaW5nX251bRgFIAEoDRITCgtOT1BCRUJLSElLQRgH",
            "IAEoDRITCgtLTU5KTk1KRkdCRxgBIAEoDUIeqgIbRWdnTGluay5EYW5oZW5n",
            "U2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.GachaItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.DoGachaScRsp), global::EggLink.DanhengServer.Proto.DoGachaScRsp.Parser, new[]{ "PENILHGLHHM", "GachaItemList", "GDIFAAHIFBH", "GachaNum", "GachaId", "Retcode", "CeilingNum", "NOPBEBKHIKA", "KMNJNMJFGBG" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DoGachaScRsp : pb::IMessage<DoGachaScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DoGachaScRsp> _parser = new pb::MessageParser<DoGachaScRsp>(() => new DoGachaScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DoGachaScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.DoGachaScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoGachaScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoGachaScRsp(DoGachaScRsp other) : this() {
      pENILHGLHHM_ = other.pENILHGLHHM_;
      gachaItemList_ = other.gachaItemList_.Clone();
      gDIFAAHIFBH_ = other.gDIFAAHIFBH_;
      gachaNum_ = other.gachaNum_;
      gachaId_ = other.gachaId_;
      retcode_ = other.retcode_;
      ceilingNum_ = other.ceilingNum_;
      nOPBEBKHIKA_ = other.nOPBEBKHIKA_;
      kMNJNMJFGBG_ = other.kMNJNMJFGBG_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DoGachaScRsp Clone() {
      return new DoGachaScRsp(this);
    }

    /// <summary>Field number for the "PENILHGLHHM" field.</summary>
    public const int PENILHGLHHMFieldNumber = 9;
    private uint pENILHGLHHM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PENILHGLHHM {
      get { return pENILHGLHHM_; }
      set {
        pENILHGLHHM_ = value;
      }
    }

    /// <summary>Field number for the "gacha_item_list" field.</summary>
    public const int GachaItemListFieldNumber = 15;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.GachaItem> _repeated_gachaItemList_codec
        = pb::FieldCodec.ForMessage(122, global::EggLink.DanhengServer.Proto.GachaItem.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.GachaItem> gachaItemList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.GachaItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.GachaItem> GachaItemList {
      get { return gachaItemList_; }
    }

    /// <summary>Field number for the "GDIFAAHIFBH" field.</summary>
    public const int GDIFAAHIFBHFieldNumber = 11;
    private uint gDIFAAHIFBH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GDIFAAHIFBH {
      get { return gDIFAAHIFBH_; }
      set {
        gDIFAAHIFBH_ = value;
      }
    }

    /// <summary>Field number for the "gacha_num" field.</summary>
    public const int GachaNumFieldNumber = 13;
    private uint gachaNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaNum {
      get { return gachaNum_; }
      set {
        gachaNum_ = value;
      }
    }

    /// <summary>Field number for the "gacha_id" field.</summary>
    public const int GachaIdFieldNumber = 8;
    private uint gachaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GachaId {
      get { return gachaId_; }
      set {
        gachaId_ = value;
      }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 14;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "ceiling_num" field.</summary>
    public const int CeilingNumFieldNumber = 5;
    private uint ceilingNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CeilingNum {
      get { return ceilingNum_; }
      set {
        ceilingNum_ = value;
      }
    }

    /// <summary>Field number for the "NOPBEBKHIKA" field.</summary>
    public const int NOPBEBKHIKAFieldNumber = 7;
    private uint nOPBEBKHIKA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NOPBEBKHIKA {
      get { return nOPBEBKHIKA_; }
      set {
        nOPBEBKHIKA_ = value;
      }
    }

    /// <summary>Field number for the "KMNJNMJFGBG" field.</summary>
    public const int KMNJNMJFGBGFieldNumber = 1;
    private uint kMNJNMJFGBG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KMNJNMJFGBG {
      get { return kMNJNMJFGBG_; }
      set {
        kMNJNMJFGBG_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DoGachaScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DoGachaScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PENILHGLHHM != other.PENILHGLHHM) return false;
      if(!gachaItemList_.Equals(other.gachaItemList_)) return false;
      if (GDIFAAHIFBH != other.GDIFAAHIFBH) return false;
      if (GachaNum != other.GachaNum) return false;
      if (GachaId != other.GachaId) return false;
      if (Retcode != other.Retcode) return false;
      if (CeilingNum != other.CeilingNum) return false;
      if (NOPBEBKHIKA != other.NOPBEBKHIKA) return false;
      if (KMNJNMJFGBG != other.KMNJNMJFGBG) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PENILHGLHHM != 0) hash ^= PENILHGLHHM.GetHashCode();
      hash ^= gachaItemList_.GetHashCode();
      if (GDIFAAHIFBH != 0) hash ^= GDIFAAHIFBH.GetHashCode();
      if (GachaNum != 0) hash ^= GachaNum.GetHashCode();
      if (GachaId != 0) hash ^= GachaId.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (CeilingNum != 0) hash ^= CeilingNum.GetHashCode();
      if (NOPBEBKHIKA != 0) hash ^= NOPBEBKHIKA.GetHashCode();
      if (KMNJNMJFGBG != 0) hash ^= KMNJNMJFGBG.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (KMNJNMJFGBG != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(KMNJNMJFGBG);
      }
      if (CeilingNum != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CeilingNum);
      }
      if (NOPBEBKHIKA != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(NOPBEBKHIKA);
      }
      if (GachaId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GachaId);
      }
      if (PENILHGLHHM != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(PENILHGLHHM);
      }
      if (GDIFAAHIFBH != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(GDIFAAHIFBH);
      }
      if (GachaNum != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(GachaNum);
      }
      if (Retcode != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Retcode);
      }
      gachaItemList_.WriteTo(output, _repeated_gachaItemList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (KMNJNMJFGBG != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(KMNJNMJFGBG);
      }
      if (CeilingNum != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CeilingNum);
      }
      if (NOPBEBKHIKA != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(NOPBEBKHIKA);
      }
      if (GachaId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GachaId);
      }
      if (PENILHGLHHM != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(PENILHGLHHM);
      }
      if (GDIFAAHIFBH != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(GDIFAAHIFBH);
      }
      if (GachaNum != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(GachaNum);
      }
      if (Retcode != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(Retcode);
      }
      gachaItemList_.WriteTo(ref output, _repeated_gachaItemList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PENILHGLHHM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PENILHGLHHM);
      }
      size += gachaItemList_.CalculateSize(_repeated_gachaItemList_codec);
      if (GDIFAAHIFBH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GDIFAAHIFBH);
      }
      if (GachaNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaNum);
      }
      if (GachaId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaId);
      }
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (CeilingNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CeilingNum);
      }
      if (NOPBEBKHIKA != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NOPBEBKHIKA);
      }
      if (KMNJNMJFGBG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KMNJNMJFGBG);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DoGachaScRsp other) {
      if (other == null) {
        return;
      }
      if (other.PENILHGLHHM != 0) {
        PENILHGLHHM = other.PENILHGLHHM;
      }
      gachaItemList_.Add(other.gachaItemList_);
      if (other.GDIFAAHIFBH != 0) {
        GDIFAAHIFBH = other.GDIFAAHIFBH;
      }
      if (other.GachaNum != 0) {
        GachaNum = other.GachaNum;
      }
      if (other.GachaId != 0) {
        GachaId = other.GachaId;
      }
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.CeilingNum != 0) {
        CeilingNum = other.CeilingNum;
      }
      if (other.NOPBEBKHIKA != 0) {
        NOPBEBKHIKA = other.NOPBEBKHIKA;
      }
      if (other.KMNJNMJFGBG != 0) {
        KMNJNMJFGBG = other.KMNJNMJFGBG;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            KMNJNMJFGBG = input.ReadUInt32();
            break;
          }
          case 40: {
            CeilingNum = input.ReadUInt32();
            break;
          }
          case 56: {
            NOPBEBKHIKA = input.ReadUInt32();
            break;
          }
          case 64: {
            GachaId = input.ReadUInt32();
            break;
          }
          case 72: {
            PENILHGLHHM = input.ReadUInt32();
            break;
          }
          case 88: {
            GDIFAAHIFBH = input.ReadUInt32();
            break;
          }
          case 104: {
            GachaNum = input.ReadUInt32();
            break;
          }
          case 112: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 122: {
            gachaItemList_.AddEntriesFrom(input, _repeated_gachaItemList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            KMNJNMJFGBG = input.ReadUInt32();
            break;
          }
          case 40: {
            CeilingNum = input.ReadUInt32();
            break;
          }
          case 56: {
            NOPBEBKHIKA = input.ReadUInt32();
            break;
          }
          case 64: {
            GachaId = input.ReadUInt32();
            break;
          }
          case 72: {
            PENILHGLHHM = input.ReadUInt32();
            break;
          }
          case 88: {
            GDIFAAHIFBH = input.ReadUInt32();
            break;
          }
          case 104: {
            GachaNum = input.ReadUInt32();
            break;
          }
          case 112: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 122: {
            gachaItemList_.AddEntriesFrom(ref input, _repeated_gachaItemList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
