// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EOJLNGDDLNN.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from EOJLNGDDLNN.proto</summary>
  public static partial class EOJLNGDDLNNReflection {

    #region Descriptor
    /// <summary>File descriptor for EOJLNGDDLNN.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EOJLNGDDLNNReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFFT0pMTkdERExOTi5wcm90bxoRSkFMTEFQUENQRkUucHJvdG8aEUhCR0hB",
            "T1BCS0pQLnByb3RvIrwBCgtFT0pMTkdERExOThITCgtQQU5CQ05JQ09IShgL",
            "IAEoDRIhCgtOQktIUEpISk1ITxgMIAMoCzIMLkhCR0hBT1BCS0pQEhMKC0pG",
            "RURKTUtNTEZPGAMgAygNEhMKC0NHTkJIS0JISUNHGAYgASgNEiEKC01EQkdH",
            "QkxFR0VNGA0gAygLMgwuSkFMTEFQUENQRkUSEwoLTkJLRUxDSElMR0cYDyAB",
            "KAgSEwoLQkxBTEpNTUhJRlAYByABKAhCHqoCG0VnZ0xpbmsuRGFuaGVuZ1Nl",
            "cnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.JALLAPPCPFEReflection.Descriptor, global::EggLink.DanhengServer.Proto.HBGHAOPBKJPReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.EOJLNGDDLNN), global::EggLink.DanhengServer.Proto.EOJLNGDDLNN.Parser, new[]{ "PANBCNICOHJ", "NBKHPJHJMHO", "JFEDJMKMLFO", "CGNBHKBHICG", "MDBGGBLEGEM", "NBKELCHILGG", "BLALJMMHIFP" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EOJLNGDDLNN : pb::IMessage<EOJLNGDDLNN>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EOJLNGDDLNN> _parser = new pb::MessageParser<EOJLNGDDLNN>(() => new EOJLNGDDLNN());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EOJLNGDDLNN> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.EOJLNGDDLNNReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EOJLNGDDLNN() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EOJLNGDDLNN(EOJLNGDDLNN other) : this() {
      pANBCNICOHJ_ = other.pANBCNICOHJ_;
      nBKHPJHJMHO_ = other.nBKHPJHJMHO_.Clone();
      jFEDJMKMLFO_ = other.jFEDJMKMLFO_.Clone();
      cGNBHKBHICG_ = other.cGNBHKBHICG_;
      mDBGGBLEGEM_ = other.mDBGGBLEGEM_.Clone();
      nBKELCHILGG_ = other.nBKELCHILGG_;
      bLALJMMHIFP_ = other.bLALJMMHIFP_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EOJLNGDDLNN Clone() {
      return new EOJLNGDDLNN(this);
    }

    /// <summary>Field number for the "PANBCNICOHJ" field.</summary>
    public const int PANBCNICOHJFieldNumber = 11;
    private uint pANBCNICOHJ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PANBCNICOHJ {
      get { return pANBCNICOHJ_; }
      set {
        pANBCNICOHJ_ = value;
      }
    }

    /// <summary>Field number for the "NBKHPJHJMHO" field.</summary>
    public const int NBKHPJHJMHOFieldNumber = 12;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.HBGHAOPBKJP> _repeated_nBKHPJHJMHO_codec
        = pb::FieldCodec.ForMessage(98, global::EggLink.DanhengServer.Proto.HBGHAOPBKJP.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HBGHAOPBKJP> nBKHPJHJMHO_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HBGHAOPBKJP>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.HBGHAOPBKJP> NBKHPJHJMHO {
      get { return nBKHPJHJMHO_; }
    }

    /// <summary>Field number for the "JFEDJMKMLFO" field.</summary>
    public const int JFEDJMKMLFOFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_jFEDJMKMLFO_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> jFEDJMKMLFO_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> JFEDJMKMLFO {
      get { return jFEDJMKMLFO_; }
    }

    /// <summary>Field number for the "CGNBHKBHICG" field.</summary>
    public const int CGNBHKBHICGFieldNumber = 6;
    private uint cGNBHKBHICG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CGNBHKBHICG {
      get { return cGNBHKBHICG_; }
      set {
        cGNBHKBHICG_ = value;
      }
    }

    /// <summary>Field number for the "MDBGGBLEGEM" field.</summary>
    public const int MDBGGBLEGEMFieldNumber = 13;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.JALLAPPCPFE> _repeated_mDBGGBLEGEM_codec
        = pb::FieldCodec.ForMessage(106, global::EggLink.DanhengServer.Proto.JALLAPPCPFE.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JALLAPPCPFE> mDBGGBLEGEM_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JALLAPPCPFE>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.JALLAPPCPFE> MDBGGBLEGEM {
      get { return mDBGGBLEGEM_; }
    }

    /// <summary>Field number for the "NBKELCHILGG" field.</summary>
    public const int NBKELCHILGGFieldNumber = 15;
    private bool nBKELCHILGG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NBKELCHILGG {
      get { return nBKELCHILGG_; }
      set {
        nBKELCHILGG_ = value;
      }
    }

    /// <summary>Field number for the "BLALJMMHIFP" field.</summary>
    public const int BLALJMMHIFPFieldNumber = 7;
    private bool bLALJMMHIFP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BLALJMMHIFP {
      get { return bLALJMMHIFP_; }
      set {
        bLALJMMHIFP_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EOJLNGDDLNN);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EOJLNGDDLNN other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PANBCNICOHJ != other.PANBCNICOHJ) return false;
      if(!nBKHPJHJMHO_.Equals(other.nBKHPJHJMHO_)) return false;
      if(!jFEDJMKMLFO_.Equals(other.jFEDJMKMLFO_)) return false;
      if (CGNBHKBHICG != other.CGNBHKBHICG) return false;
      if(!mDBGGBLEGEM_.Equals(other.mDBGGBLEGEM_)) return false;
      if (NBKELCHILGG != other.NBKELCHILGG) return false;
      if (BLALJMMHIFP != other.BLALJMMHIFP) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PANBCNICOHJ != 0) hash ^= PANBCNICOHJ.GetHashCode();
      hash ^= nBKHPJHJMHO_.GetHashCode();
      hash ^= jFEDJMKMLFO_.GetHashCode();
      if (CGNBHKBHICG != 0) hash ^= CGNBHKBHICG.GetHashCode();
      hash ^= mDBGGBLEGEM_.GetHashCode();
      if (NBKELCHILGG != false) hash ^= NBKELCHILGG.GetHashCode();
      if (BLALJMMHIFP != false) hash ^= BLALJMMHIFP.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      jFEDJMKMLFO_.WriteTo(output, _repeated_jFEDJMKMLFO_codec);
      if (CGNBHKBHICG != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(CGNBHKBHICG);
      }
      if (BLALJMMHIFP != false) {
        output.WriteRawTag(56);
        output.WriteBool(BLALJMMHIFP);
      }
      if (PANBCNICOHJ != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(PANBCNICOHJ);
      }
      nBKHPJHJMHO_.WriteTo(output, _repeated_nBKHPJHJMHO_codec);
      mDBGGBLEGEM_.WriteTo(output, _repeated_mDBGGBLEGEM_codec);
      if (NBKELCHILGG != false) {
        output.WriteRawTag(120);
        output.WriteBool(NBKELCHILGG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      jFEDJMKMLFO_.WriteTo(ref output, _repeated_jFEDJMKMLFO_codec);
      if (CGNBHKBHICG != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(CGNBHKBHICG);
      }
      if (BLALJMMHIFP != false) {
        output.WriteRawTag(56);
        output.WriteBool(BLALJMMHIFP);
      }
      if (PANBCNICOHJ != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(PANBCNICOHJ);
      }
      nBKHPJHJMHO_.WriteTo(ref output, _repeated_nBKHPJHJMHO_codec);
      mDBGGBLEGEM_.WriteTo(ref output, _repeated_mDBGGBLEGEM_codec);
      if (NBKELCHILGG != false) {
        output.WriteRawTag(120);
        output.WriteBool(NBKELCHILGG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PANBCNICOHJ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PANBCNICOHJ);
      }
      size += nBKHPJHJMHO_.CalculateSize(_repeated_nBKHPJHJMHO_codec);
      size += jFEDJMKMLFO_.CalculateSize(_repeated_jFEDJMKMLFO_codec);
      if (CGNBHKBHICG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CGNBHKBHICG);
      }
      size += mDBGGBLEGEM_.CalculateSize(_repeated_mDBGGBLEGEM_codec);
      if (NBKELCHILGG != false) {
        size += 1 + 1;
      }
      if (BLALJMMHIFP != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EOJLNGDDLNN other) {
      if (other == null) {
        return;
      }
      if (other.PANBCNICOHJ != 0) {
        PANBCNICOHJ = other.PANBCNICOHJ;
      }
      nBKHPJHJMHO_.Add(other.nBKHPJHJMHO_);
      jFEDJMKMLFO_.Add(other.jFEDJMKMLFO_);
      if (other.CGNBHKBHICG != 0) {
        CGNBHKBHICG = other.CGNBHKBHICG;
      }
      mDBGGBLEGEM_.Add(other.mDBGGBLEGEM_);
      if (other.NBKELCHILGG != false) {
        NBKELCHILGG = other.NBKELCHILGG;
      }
      if (other.BLALJMMHIFP != false) {
        BLALJMMHIFP = other.BLALJMMHIFP;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26:
          case 24: {
            jFEDJMKMLFO_.AddEntriesFrom(input, _repeated_jFEDJMKMLFO_codec);
            break;
          }
          case 48: {
            CGNBHKBHICG = input.ReadUInt32();
            break;
          }
          case 56: {
            BLALJMMHIFP = input.ReadBool();
            break;
          }
          case 88: {
            PANBCNICOHJ = input.ReadUInt32();
            break;
          }
          case 98: {
            nBKHPJHJMHO_.AddEntriesFrom(input, _repeated_nBKHPJHJMHO_codec);
            break;
          }
          case 106: {
            mDBGGBLEGEM_.AddEntriesFrom(input, _repeated_mDBGGBLEGEM_codec);
            break;
          }
          case 120: {
            NBKELCHILGG = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26:
          case 24: {
            jFEDJMKMLFO_.AddEntriesFrom(ref input, _repeated_jFEDJMKMLFO_codec);
            break;
          }
          case 48: {
            CGNBHKBHICG = input.ReadUInt32();
            break;
          }
          case 56: {
            BLALJMMHIFP = input.ReadBool();
            break;
          }
          case 88: {
            PANBCNICOHJ = input.ReadUInt32();
            break;
          }
          case 98: {
            nBKHPJHJMHO_.AddEntriesFrom(ref input, _repeated_nBKHPJHJMHO_codec);
            break;
          }
          case 106: {
            mDBGGBLEGEM_.AddEntriesFrom(ref input, _repeated_mDBGGBLEGEM_codec);
            break;
          }
          case 120: {
            NBKELCHILGG = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
