// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FLNIDKIGGBK.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from FLNIDKIGGBK.proto</summary>
  public static partial class FLNIDKIGGBKReflection {

    #region Descriptor
    /// <summary>File descriptor for FLNIDKIGGBK.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FLNIDKIGGBKReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFGTE5JREtJR0dCSy5wcm90bxoRTlBBSUlORUtFRkIucHJvdG8aEUlJS05H",
            "TkhETUZJLnByb3RvIrUBCgtGTE5JREtJR0dCSxIhCgtQRUhJTkdKS0dDQhgP",
            "IAEoCzIMLklJS05HTkhETUZJEhMKC0dKUEFOT0NOR0JNGAggASgNEhMKC0RL",
            "SElHQ0lQRUtGGAsgASgIEhMKC0JLTUFNR0FQRUdIGAIgASgNEiEKC0tORUlO",
            "TU5MQ0RJGAwgASgLMgwuSUlLTkdOSERNRkkSIQoLT0VCQUZCSUdNQkMYCSAD",
            "KAsyDC5OUEFJSU5FS0VGQkIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlBy",
            "b3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.NPAIINEKEFBReflection.Descriptor, global::EggLink.DanhengServer.Proto.IIKNGNHDMFIReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.FLNIDKIGGBK), global::EggLink.DanhengServer.Proto.FLNIDKIGGBK.Parser, new[]{ "PEHINGJKGCB", "GJPANOCNGBM", "DKHIGCIPEKF", "BKMAMGAPEGH", "KNEINMNLCDI", "OEBAFBIGMBC" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FLNIDKIGGBK : pb::IMessage<FLNIDKIGGBK>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FLNIDKIGGBK> _parser = new pb::MessageParser<FLNIDKIGGBK>(() => new FLNIDKIGGBK());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FLNIDKIGGBK> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.FLNIDKIGGBKReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FLNIDKIGGBK() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FLNIDKIGGBK(FLNIDKIGGBK other) : this() {
      pEHINGJKGCB_ = other.pEHINGJKGCB_ != null ? other.pEHINGJKGCB_.Clone() : null;
      gJPANOCNGBM_ = other.gJPANOCNGBM_;
      dKHIGCIPEKF_ = other.dKHIGCIPEKF_;
      bKMAMGAPEGH_ = other.bKMAMGAPEGH_;
      kNEINMNLCDI_ = other.kNEINMNLCDI_ != null ? other.kNEINMNLCDI_.Clone() : null;
      oEBAFBIGMBC_ = other.oEBAFBIGMBC_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FLNIDKIGGBK Clone() {
      return new FLNIDKIGGBK(this);
    }

    /// <summary>Field number for the "PEHINGJKGCB" field.</summary>
    public const int PEHINGJKGCBFieldNumber = 15;
    private global::EggLink.DanhengServer.Proto.IIKNGNHDMFI pEHINGJKGCB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.IIKNGNHDMFI PEHINGJKGCB {
      get { return pEHINGJKGCB_; }
      set {
        pEHINGJKGCB_ = value;
      }
    }

    /// <summary>Field number for the "GJPANOCNGBM" field.</summary>
    public const int GJPANOCNGBMFieldNumber = 8;
    private uint gJPANOCNGBM_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GJPANOCNGBM {
      get { return gJPANOCNGBM_; }
      set {
        gJPANOCNGBM_ = value;
      }
    }

    /// <summary>Field number for the "DKHIGCIPEKF" field.</summary>
    public const int DKHIGCIPEKFFieldNumber = 11;
    private bool dKHIGCIPEKF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DKHIGCIPEKF {
      get { return dKHIGCIPEKF_; }
      set {
        dKHIGCIPEKF_ = value;
      }
    }

    /// <summary>Field number for the "BKMAMGAPEGH" field.</summary>
    public const int BKMAMGAPEGHFieldNumber = 2;
    private uint bKMAMGAPEGH_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BKMAMGAPEGH {
      get { return bKMAMGAPEGH_; }
      set {
        bKMAMGAPEGH_ = value;
      }
    }

    /// <summary>Field number for the "KNEINMNLCDI" field.</summary>
    public const int KNEINMNLCDIFieldNumber = 12;
    private global::EggLink.DanhengServer.Proto.IIKNGNHDMFI kNEINMNLCDI_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.IIKNGNHDMFI KNEINMNLCDI {
      get { return kNEINMNLCDI_; }
      set {
        kNEINMNLCDI_ = value;
      }
    }

    /// <summary>Field number for the "OEBAFBIGMBC" field.</summary>
    public const int OEBAFBIGMBCFieldNumber = 9;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.NPAIINEKEFB> _repeated_oEBAFBIGMBC_codec
        = pb::FieldCodec.ForMessage(74, global::EggLink.DanhengServer.Proto.NPAIINEKEFB.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.NPAIINEKEFB> oEBAFBIGMBC_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.NPAIINEKEFB>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.NPAIINEKEFB> OEBAFBIGMBC {
      get { return oEBAFBIGMBC_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FLNIDKIGGBK);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FLNIDKIGGBK other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PEHINGJKGCB, other.PEHINGJKGCB)) return false;
      if (GJPANOCNGBM != other.GJPANOCNGBM) return false;
      if (DKHIGCIPEKF != other.DKHIGCIPEKF) return false;
      if (BKMAMGAPEGH != other.BKMAMGAPEGH) return false;
      if (!object.Equals(KNEINMNLCDI, other.KNEINMNLCDI)) return false;
      if(!oEBAFBIGMBC_.Equals(other.oEBAFBIGMBC_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pEHINGJKGCB_ != null) hash ^= PEHINGJKGCB.GetHashCode();
      if (GJPANOCNGBM != 0) hash ^= GJPANOCNGBM.GetHashCode();
      if (DKHIGCIPEKF != false) hash ^= DKHIGCIPEKF.GetHashCode();
      if (BKMAMGAPEGH != 0) hash ^= BKMAMGAPEGH.GetHashCode();
      if (kNEINMNLCDI_ != null) hash ^= KNEINMNLCDI.GetHashCode();
      hash ^= oEBAFBIGMBC_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BKMAMGAPEGH != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(BKMAMGAPEGH);
      }
      if (GJPANOCNGBM != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GJPANOCNGBM);
      }
      oEBAFBIGMBC_.WriteTo(output, _repeated_oEBAFBIGMBC_codec);
      if (DKHIGCIPEKF != false) {
        output.WriteRawTag(88);
        output.WriteBool(DKHIGCIPEKF);
      }
      if (kNEINMNLCDI_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(KNEINMNLCDI);
      }
      if (pEHINGJKGCB_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(PEHINGJKGCB);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BKMAMGAPEGH != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(BKMAMGAPEGH);
      }
      if (GJPANOCNGBM != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GJPANOCNGBM);
      }
      oEBAFBIGMBC_.WriteTo(ref output, _repeated_oEBAFBIGMBC_codec);
      if (DKHIGCIPEKF != false) {
        output.WriteRawTag(88);
        output.WriteBool(DKHIGCIPEKF);
      }
      if (kNEINMNLCDI_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(KNEINMNLCDI);
      }
      if (pEHINGJKGCB_ != null) {
        output.WriteRawTag(122);
        output.WriteMessage(PEHINGJKGCB);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pEHINGJKGCB_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PEHINGJKGCB);
      }
      if (GJPANOCNGBM != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GJPANOCNGBM);
      }
      if (DKHIGCIPEKF != false) {
        size += 1 + 1;
      }
      if (BKMAMGAPEGH != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BKMAMGAPEGH);
      }
      if (kNEINMNLCDI_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KNEINMNLCDI);
      }
      size += oEBAFBIGMBC_.CalculateSize(_repeated_oEBAFBIGMBC_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FLNIDKIGGBK other) {
      if (other == null) {
        return;
      }
      if (other.pEHINGJKGCB_ != null) {
        if (pEHINGJKGCB_ == null) {
          PEHINGJKGCB = new global::EggLink.DanhengServer.Proto.IIKNGNHDMFI();
        }
        PEHINGJKGCB.MergeFrom(other.PEHINGJKGCB);
      }
      if (other.GJPANOCNGBM != 0) {
        GJPANOCNGBM = other.GJPANOCNGBM;
      }
      if (other.DKHIGCIPEKF != false) {
        DKHIGCIPEKF = other.DKHIGCIPEKF;
      }
      if (other.BKMAMGAPEGH != 0) {
        BKMAMGAPEGH = other.BKMAMGAPEGH;
      }
      if (other.kNEINMNLCDI_ != null) {
        if (kNEINMNLCDI_ == null) {
          KNEINMNLCDI = new global::EggLink.DanhengServer.Proto.IIKNGNHDMFI();
        }
        KNEINMNLCDI.MergeFrom(other.KNEINMNLCDI);
      }
      oEBAFBIGMBC_.Add(other.oEBAFBIGMBC_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            BKMAMGAPEGH = input.ReadUInt32();
            break;
          }
          case 64: {
            GJPANOCNGBM = input.ReadUInt32();
            break;
          }
          case 74: {
            oEBAFBIGMBC_.AddEntriesFrom(input, _repeated_oEBAFBIGMBC_codec);
            break;
          }
          case 88: {
            DKHIGCIPEKF = input.ReadBool();
            break;
          }
          case 98: {
            if (kNEINMNLCDI_ == null) {
              KNEINMNLCDI = new global::EggLink.DanhengServer.Proto.IIKNGNHDMFI();
            }
            input.ReadMessage(KNEINMNLCDI);
            break;
          }
          case 122: {
            if (pEHINGJKGCB_ == null) {
              PEHINGJKGCB = new global::EggLink.DanhengServer.Proto.IIKNGNHDMFI();
            }
            input.ReadMessage(PEHINGJKGCB);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            BKMAMGAPEGH = input.ReadUInt32();
            break;
          }
          case 64: {
            GJPANOCNGBM = input.ReadUInt32();
            break;
          }
          case 74: {
            oEBAFBIGMBC_.AddEntriesFrom(ref input, _repeated_oEBAFBIGMBC_codec);
            break;
          }
          case 88: {
            DKHIGCIPEKF = input.ReadBool();
            break;
          }
          case 98: {
            if (kNEINMNLCDI_ == null) {
              KNEINMNLCDI = new global::EggLink.DanhengServer.Proto.IIKNGNHDMFI();
            }
            input.ReadMessage(KNEINMNLCDI);
            break;
          }
          case 122: {
            if (pEHINGJKGCB_ == null) {
              PEHINGJKGCB = new global::EggLink.DanhengServer.Proto.IIKNGNHDMFI();
            }
            input.ReadMessage(PEHINGJKGCB);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
