// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KLAAHJHNLCJ.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from KLAAHJHNLCJ.proto</summary>
  public static partial class KLAAHJHNLCJReflection {

    #region Descriptor
    /// <summary>File descriptor for KLAAHJHNLCJ.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KLAAHJHNLCJReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFLTEFBSEpITkxDSi5wcm90byJJCgtLTEFBSEpITkxDShIQCghwcm9ncmVz",
            "cxgGIAEoDRITCgtDRElBSktFSkRIQRgLIAEoCBITCgtCSFBDTk5GT0tFRRgO",
            "IAEoDUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.KLAAHJHNLCJ), global::EggLink.DanhengServer.Proto.KLAAHJHNLCJ.Parser, new[]{ "Progress", "CDIAJKEJDHA", "BHPCNNFOKEE" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KLAAHJHNLCJ : pb::IMessage<KLAAHJHNLCJ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KLAAHJHNLCJ> _parser = new pb::MessageParser<KLAAHJHNLCJ>(() => new KLAAHJHNLCJ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KLAAHJHNLCJ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.KLAAHJHNLCJReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KLAAHJHNLCJ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KLAAHJHNLCJ(KLAAHJHNLCJ other) : this() {
      progress_ = other.progress_;
      cDIAJKEJDHA_ = other.cDIAJKEJDHA_;
      bHPCNNFOKEE_ = other.bHPCNNFOKEE_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KLAAHJHNLCJ Clone() {
      return new KLAAHJHNLCJ(this);
    }

    /// <summary>Field number for the "progress" field.</summary>
    public const int ProgressFieldNumber = 6;
    private uint progress_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Progress {
      get { return progress_; }
      set {
        progress_ = value;
      }
    }

    /// <summary>Field number for the "CDIAJKEJDHA" field.</summary>
    public const int CDIAJKEJDHAFieldNumber = 11;
    private bool cDIAJKEJDHA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CDIAJKEJDHA {
      get { return cDIAJKEJDHA_; }
      set {
        cDIAJKEJDHA_ = value;
      }
    }

    /// <summary>Field number for the "BHPCNNFOKEE" field.</summary>
    public const int BHPCNNFOKEEFieldNumber = 14;
    private uint bHPCNNFOKEE_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BHPCNNFOKEE {
      get { return bHPCNNFOKEE_; }
      set {
        bHPCNNFOKEE_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KLAAHJHNLCJ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KLAAHJHNLCJ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Progress != other.Progress) return false;
      if (CDIAJKEJDHA != other.CDIAJKEJDHA) return false;
      if (BHPCNNFOKEE != other.BHPCNNFOKEE) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Progress != 0) hash ^= Progress.GetHashCode();
      if (CDIAJKEJDHA != false) hash ^= CDIAJKEJDHA.GetHashCode();
      if (BHPCNNFOKEE != 0) hash ^= BHPCNNFOKEE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Progress != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Progress);
      }
      if (CDIAJKEJDHA != false) {
        output.WriteRawTag(88);
        output.WriteBool(CDIAJKEJDHA);
      }
      if (BHPCNNFOKEE != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(BHPCNNFOKEE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Progress != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(Progress);
      }
      if (CDIAJKEJDHA != false) {
        output.WriteRawTag(88);
        output.WriteBool(CDIAJKEJDHA);
      }
      if (BHPCNNFOKEE != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(BHPCNNFOKEE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Progress != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Progress);
      }
      if (CDIAJKEJDHA != false) {
        size += 1 + 1;
      }
      if (BHPCNNFOKEE != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BHPCNNFOKEE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KLAAHJHNLCJ other) {
      if (other == null) {
        return;
      }
      if (other.Progress != 0) {
        Progress = other.Progress;
      }
      if (other.CDIAJKEJDHA != false) {
        CDIAJKEJDHA = other.CDIAJKEJDHA;
      }
      if (other.BHPCNNFOKEE != 0) {
        BHPCNNFOKEE = other.BHPCNNFOKEE;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 48: {
            Progress = input.ReadUInt32();
            break;
          }
          case 88: {
            CDIAJKEJDHA = input.ReadBool();
            break;
          }
          case 112: {
            BHPCNNFOKEE = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 48: {
            Progress = input.ReadUInt32();
            break;
          }
          case 88: {
            CDIAJKEJDHA = input.ReadBool();
            break;
          }
          case 112: {
            BHPCNNFOKEE = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
