// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KNCHLMGILJC.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from KNCHLMGILJC.proto</summary>
  public static partial class KNCHLMGILJCReflection {

    #region Descriptor
    /// <summary>File descriptor for KNCHLMGILJC.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KNCHLMGILJCReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFLTkNITE1HSUxKQy5wcm90bxoRRUpCSU9LTU9MQUYucHJvdG8iqgEKC0tO",
            "Q0hMTUdJTEpDEhMKC05PUERLTERFS0tGGAcgASgNEhAKCHBhbmVsX2lkGAgg",
            "ASgNEjIKC01CR0lKTkpGSEdFGAYgAygLMh0uS05DSExNR0lMSkMuTUJHSUpO",
            "SkZIR0VFbnRyeRpAChBNQkdJSk5KRkhHRUVudHJ5EgsKA2tleRgBIAEoDRIb",
            "CgV2YWx1ZRgCIAEoCzIMLkVKQklPS01PTEFGOgI4AUIeqgIbRWdnTGluay5E",
            "YW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.EJBIOKMOLAFReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.KNCHLMGILJC), global::EggLink.DanhengServer.Proto.KNCHLMGILJC.Parser, new[]{ "NOPDKLDEKKF", "PanelId", "MBGIJNJFHGE" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class KNCHLMGILJC : pb::IMessage<KNCHLMGILJC>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KNCHLMGILJC> _parser = new pb::MessageParser<KNCHLMGILJC>(() => new KNCHLMGILJC());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KNCHLMGILJC> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.KNCHLMGILJCReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KNCHLMGILJC() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KNCHLMGILJC(KNCHLMGILJC other) : this() {
      nOPDKLDEKKF_ = other.nOPDKLDEKKF_;
      panelId_ = other.panelId_;
      mBGIJNJFHGE_ = other.mBGIJNJFHGE_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KNCHLMGILJC Clone() {
      return new KNCHLMGILJC(this);
    }

    /// <summary>Field number for the "NOPDKLDEKKF" field.</summary>
    public const int NOPDKLDEKKFFieldNumber = 7;
    private uint nOPDKLDEKKF_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NOPDKLDEKKF {
      get { return nOPDKLDEKKF_; }
      set {
        nOPDKLDEKKF_ = value;
      }
    }

    /// <summary>Field number for the "panel_id" field.</summary>
    public const int PanelIdFieldNumber = 8;
    private uint panelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PanelId {
      get { return panelId_; }
      set {
        panelId_ = value;
      }
    }

    /// <summary>Field number for the "MBGIJNJFHGE" field.</summary>
    public const int MBGIJNJFHGEFieldNumber = 6;
    private static readonly pbc::MapField<uint, global::EggLink.DanhengServer.Proto.EJBIOKMOLAF>.Codec _map_mBGIJNJFHGE_codec
        = new pbc::MapField<uint, global::EggLink.DanhengServer.Proto.EJBIOKMOLAF>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForMessage(18, global::EggLink.DanhengServer.Proto.EJBIOKMOLAF.Parser), 50);
    private readonly pbc::MapField<uint, global::EggLink.DanhengServer.Proto.EJBIOKMOLAF> mBGIJNJFHGE_ = new pbc::MapField<uint, global::EggLink.DanhengServer.Proto.EJBIOKMOLAF>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, global::EggLink.DanhengServer.Proto.EJBIOKMOLAF> MBGIJNJFHGE {
      get { return mBGIJNJFHGE_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KNCHLMGILJC);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KNCHLMGILJC other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NOPDKLDEKKF != other.NOPDKLDEKKF) return false;
      if (PanelId != other.PanelId) return false;
      if (!MBGIJNJFHGE.Equals(other.MBGIJNJFHGE)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NOPDKLDEKKF != 0) hash ^= NOPDKLDEKKF.GetHashCode();
      if (PanelId != 0) hash ^= PanelId.GetHashCode();
      hash ^= MBGIJNJFHGE.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      mBGIJNJFHGE_.WriteTo(output, _map_mBGIJNJFHGE_codec);
      if (NOPDKLDEKKF != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(NOPDKLDEKKF);
      }
      if (PanelId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(PanelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      mBGIJNJFHGE_.WriteTo(ref output, _map_mBGIJNJFHGE_codec);
      if (NOPDKLDEKKF != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(NOPDKLDEKKF);
      }
      if (PanelId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(PanelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NOPDKLDEKKF != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NOPDKLDEKKF);
      }
      if (PanelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PanelId);
      }
      size += mBGIJNJFHGE_.CalculateSize(_map_mBGIJNJFHGE_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KNCHLMGILJC other) {
      if (other == null) {
        return;
      }
      if (other.NOPDKLDEKKF != 0) {
        NOPDKLDEKKF = other.NOPDKLDEKKF;
      }
      if (other.PanelId != 0) {
        PanelId = other.PanelId;
      }
      mBGIJNJFHGE_.MergeFrom(other.mBGIJNJFHGE_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 50: {
            mBGIJNJFHGE_.AddEntriesFrom(input, _map_mBGIJNJFHGE_codec);
            break;
          }
          case 56: {
            NOPDKLDEKKF = input.ReadUInt32();
            break;
          }
          case 64: {
            PanelId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 50: {
            mBGIJNJFHGE_.AddEntriesFrom(ref input, _map_mBGIJNJFHGE_codec);
            break;
          }
          case 56: {
            NOPDKLDEKKF = input.ReadUInt32();
            break;
          }
          case 64: {
            PanelId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
