// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OHDNCHFGFMA.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from OHDNCHFGFMA.proto</summary>
  public static partial class OHDNCHFGFMAReflection {

    #region Descriptor
    /// <summary>File descriptor for OHDNCHFGFMA.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OHDNCHFGFMAReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFPSEROQ0hGR0ZNQS5wcm90byJdCgtPSEROQ0hGR0ZNQRIQCghwYW5lbF9p",
            "ZBgPIAEoDRISCgpkdXJhYmlsaXR5GAwgASgNEhMKC0xDTE1IRUdER0dCGAog",
            "ASgNEhMKC0JKRkJHTEJKQk5OGAcgASgNQh6qAhtFZ2dMaW5rLkRhbmhlbmdT",
            "ZXJ2ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.OHDNCHFGFMA), global::EggLink.DanhengServer.Proto.OHDNCHFGFMA.Parser, new[]{ "PanelId", "Durability", "LCLMHEGDGGB", "BJFBGLBJBNN" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OHDNCHFGFMA : pb::IMessage<OHDNCHFGFMA>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OHDNCHFGFMA> _parser = new pb::MessageParser<OHDNCHFGFMA>(() => new OHDNCHFGFMA());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OHDNCHFGFMA> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.OHDNCHFGFMAReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OHDNCHFGFMA() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OHDNCHFGFMA(OHDNCHFGFMA other) : this() {
      panelId_ = other.panelId_;
      durability_ = other.durability_;
      lCLMHEGDGGB_ = other.lCLMHEGDGGB_;
      bJFBGLBJBNN_ = other.bJFBGLBJBNN_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OHDNCHFGFMA Clone() {
      return new OHDNCHFGFMA(this);
    }

    /// <summary>Field number for the "panel_id" field.</summary>
    public const int PanelIdFieldNumber = 15;
    private uint panelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PanelId {
      get { return panelId_; }
      set {
        panelId_ = value;
      }
    }

    /// <summary>Field number for the "durability" field.</summary>
    public const int DurabilityFieldNumber = 12;
    private uint durability_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Durability {
      get { return durability_; }
      set {
        durability_ = value;
      }
    }

    /// <summary>Field number for the "LCLMHEGDGGB" field.</summary>
    public const int LCLMHEGDGGBFieldNumber = 10;
    private uint lCLMHEGDGGB_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LCLMHEGDGGB {
      get { return lCLMHEGDGGB_; }
      set {
        lCLMHEGDGGB_ = value;
      }
    }

    /// <summary>Field number for the "BJFBGLBJBNN" field.</summary>
    public const int BJFBGLBJBNNFieldNumber = 7;
    private uint bJFBGLBJBNN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BJFBGLBJBNN {
      get { return bJFBGLBJBNN_; }
      set {
        bJFBGLBJBNN_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OHDNCHFGFMA);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OHDNCHFGFMA other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PanelId != other.PanelId) return false;
      if (Durability != other.Durability) return false;
      if (LCLMHEGDGGB != other.LCLMHEGDGGB) return false;
      if (BJFBGLBJBNN != other.BJFBGLBJBNN) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PanelId != 0) hash ^= PanelId.GetHashCode();
      if (Durability != 0) hash ^= Durability.GetHashCode();
      if (LCLMHEGDGGB != 0) hash ^= LCLMHEGDGGB.GetHashCode();
      if (BJFBGLBJBNN != 0) hash ^= BJFBGLBJBNN.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BJFBGLBJBNN != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(BJFBGLBJBNN);
      }
      if (LCLMHEGDGGB != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(LCLMHEGDGGB);
      }
      if (Durability != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(Durability);
      }
      if (PanelId != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(PanelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BJFBGLBJBNN != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(BJFBGLBJBNN);
      }
      if (LCLMHEGDGGB != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(LCLMHEGDGGB);
      }
      if (Durability != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(Durability);
      }
      if (PanelId != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(PanelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PanelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PanelId);
      }
      if (Durability != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Durability);
      }
      if (LCLMHEGDGGB != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LCLMHEGDGGB);
      }
      if (BJFBGLBJBNN != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BJFBGLBJBNN);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OHDNCHFGFMA other) {
      if (other == null) {
        return;
      }
      if (other.PanelId != 0) {
        PanelId = other.PanelId;
      }
      if (other.Durability != 0) {
        Durability = other.Durability;
      }
      if (other.LCLMHEGDGGB != 0) {
        LCLMHEGDGGB = other.LCLMHEGDGGB;
      }
      if (other.BJFBGLBJBNN != 0) {
        BJFBGLBJBNN = other.BJFBGLBJBNN;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 56: {
            BJFBGLBJBNN = input.ReadUInt32();
            break;
          }
          case 80: {
            LCLMHEGDGGB = input.ReadUInt32();
            break;
          }
          case 96: {
            Durability = input.ReadUInt32();
            break;
          }
          case 120: {
            PanelId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 56: {
            BJFBGLBJBNN = input.ReadUInt32();
            break;
          }
          case 80: {
            LCLMHEGDGGB = input.ReadUInt32();
            break;
          }
          case 96: {
            Durability = input.ReadUInt32();
            break;
          }
          case 120: {
            PanelId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
