// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerSimpleInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from PlayerSimpleInfo.proto</summary>
  public static partial class PlayerSimpleInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerSimpleInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerSimpleInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZQbGF5ZXJTaW1wbGVJbmZvLnByb3RvGhhGcmllbmRPbmxpbmVTdGF0dXMu",
            "cHJvdG8aE0hlYWRGcmFtZUluZm8ucHJvdG8aFlBsYXllck91dGZpdEluZm8u",
            "cHJvdG8aElBsYXRmb3JtVHlwZS5wcm90bxoWQXNzaXN0U2ltcGxlSW5mby5w",
            "cm90byKxAwoQUGxheWVyU2ltcGxlSW5mbxIQCghJc0Jhbm5lZBgEIAEoCBIR",
            "CglTaWduYXR1cmUYAyABKAkSEAoISGVhZEljb24YAiABKA0SKQoOQXNzaXN0",
            "SW5mb0xpc3QYCCADKAsyES5Bc3Npc3RTaW1wbGVJbmZvEhAKCE5pY2tuYW1l",
            "GA4gASgJEisKEFBsYXllck91dGZpdERhdGEYBSABKAsyES5QbGF5ZXJPdXRm",
            "aXRJbmZvEg0KBUxldmVsGAkgASgNEhIKCkxvZ291dFRpbWUYASABKAMSHwoI",
            "UGxhdGZvcm0YCyABKA4yDS5QbGF0Zm9ybVR5cGUSFAoMUGxhdGZvcm1VdWlk",
            "GAogASgJEioKEUhlYWRJY29uRnJhbWVJbmZvGIwIIAEoCzIOLkhlYWRGcmFt",
            "ZUluZm8SEgoKQ2hhdEJ1YmJsZRgGIAEoDRIUCgxQbGF0Zm9ybU5pY2sYByAB",
            "KAkSFAoMUGVyc29uYWxDYXJkGAwgASgNEikKDE9ubGluZVN0YXR1cxgPIAEo",
            "DjITLkZyaWVuZE9ubGluZVN0YXR1cxILCgNVaWQYDSABKA1CHqoCG0VnZ0xp",
            "bmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.FriendOnlineStatusReflection.Descriptor, global::EggLink.DanhengServer.Proto.HeadFrameInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.PlayerOutfitInfoReflection.Descriptor, global::EggLink.DanhengServer.Proto.PlatformTypeReflection.Descriptor, global::EggLink.DanhengServer.Proto.AssistSimpleInfoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.PlayerSimpleInfo), global::EggLink.DanhengServer.Proto.PlayerSimpleInfo.Parser, new[]{ "IsBanned", "Signature", "HeadIcon", "AssistInfoList", "Nickname", "PlayerOutfitData", "Level", "LogoutTime", "Platform", "PlatformUuid", "HeadIconFrameInfo", "ChatBubble", "PlatformNick", "PersonalCard", "OnlineStatus", "Uid" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerSimpleInfo : pb::IMessage<PlayerSimpleInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerSimpleInfo> _parser = new pb::MessageParser<PlayerSimpleInfo>(() => new PlayerSimpleInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerSimpleInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.PlayerSimpleInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSimpleInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSimpleInfo(PlayerSimpleInfo other) : this() {
      isBanned_ = other.isBanned_;
      signature_ = other.signature_;
      headIcon_ = other.headIcon_;
      assistInfoList_ = other.assistInfoList_.Clone();
      nickname_ = other.nickname_;
      playerOutfitData_ = other.playerOutfitData_ != null ? other.playerOutfitData_.Clone() : null;
      level_ = other.level_;
      logoutTime_ = other.logoutTime_;
      platform_ = other.platform_;
      platformUuid_ = other.platformUuid_;
      headIconFrameInfo_ = other.headIconFrameInfo_ != null ? other.headIconFrameInfo_.Clone() : null;
      chatBubble_ = other.chatBubble_;
      platformNick_ = other.platformNick_;
      personalCard_ = other.personalCard_;
      onlineStatus_ = other.onlineStatus_;
      uid_ = other.uid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerSimpleInfo Clone() {
      return new PlayerSimpleInfo(this);
    }

    /// <summary>Field number for the "IsBanned" field.</summary>
    public const int IsBannedFieldNumber = 4;
    private bool isBanned_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsBanned {
      get { return isBanned_; }
      set {
        isBanned_ = value;
      }
    }

    /// <summary>Field number for the "Signature" field.</summary>
    public const int SignatureFieldNumber = 3;
    private string signature_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Signature {
      get { return signature_; }
      set {
        signature_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HeadIcon" field.</summary>
    public const int HeadIconFieldNumber = 2;
    private uint headIcon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint HeadIcon {
      get { return headIcon_; }
      set {
        headIcon_ = value;
      }
    }

    /// <summary>Field number for the "AssistInfoList" field.</summary>
    public const int AssistInfoListFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.AssistSimpleInfo> _repeated_assistInfoList_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.AssistSimpleInfo.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.AssistSimpleInfo> assistInfoList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.AssistSimpleInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.AssistSimpleInfo> AssistInfoList {
      get { return assistInfoList_; }
    }

    /// <summary>Field number for the "Nickname" field.</summary>
    public const int NicknameFieldNumber = 14;
    private string nickname_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Nickname {
      get { return nickname_; }
      set {
        nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PlayerOutfitData" field.</summary>
    public const int PlayerOutfitDataFieldNumber = 5;
    private global::EggLink.DanhengServer.Proto.PlayerOutfitInfo playerOutfitData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PlayerOutfitInfo PlayerOutfitData {
      get { return playerOutfitData_; }
      set {
        playerOutfitData_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 9;
    private uint level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "LogoutTime" field.</summary>
    public const int LogoutTimeFieldNumber = 1;
    private long logoutTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long LogoutTime {
      get { return logoutTime_; }
      set {
        logoutTime_ = value;
      }
    }

    /// <summary>Field number for the "Platform" field.</summary>
    public const int PlatformFieldNumber = 11;
    private global::EggLink.DanhengServer.Proto.PlatformType platform_ = global::EggLink.DanhengServer.Proto.PlatformType.Editor;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.PlatformType Platform {
      get { return platform_; }
      set {
        platform_ = value;
      }
    }

    /// <summary>Field number for the "PlatformUuid" field.</summary>
    public const int PlatformUuidFieldNumber = 10;
    private string platformUuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlatformUuid {
      get { return platformUuid_; }
      set {
        platformUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "HeadIconFrameInfo" field.</summary>
    public const int HeadIconFrameInfoFieldNumber = 1036;
    private global::EggLink.DanhengServer.Proto.HeadFrameInfo headIconFrameInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.HeadFrameInfo HeadIconFrameInfo {
      get { return headIconFrameInfo_; }
      set {
        headIconFrameInfo_ = value;
      }
    }

    /// <summary>Field number for the "ChatBubble" field.</summary>
    public const int ChatBubbleFieldNumber = 6;
    private uint chatBubble_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChatBubble {
      get { return chatBubble_; }
      set {
        chatBubble_ = value;
      }
    }

    /// <summary>Field number for the "PlatformNick" field.</summary>
    public const int PlatformNickFieldNumber = 7;
    private string platformNick_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PlatformNick {
      get { return platformNick_; }
      set {
        platformNick_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PersonalCard" field.</summary>
    public const int PersonalCardFieldNumber = 12;
    private uint personalCard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PersonalCard {
      get { return personalCard_; }
      set {
        personalCard_ = value;
      }
    }

    /// <summary>Field number for the "OnlineStatus" field.</summary>
    public const int OnlineStatusFieldNumber = 15;
    private global::EggLink.DanhengServer.Proto.FriendOnlineStatus onlineStatus_ = global::EggLink.DanhengServer.Proto.FriendOnlineStatus.Offline;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.FriendOnlineStatus OnlineStatus {
      get { return onlineStatus_; }
      set {
        onlineStatus_ = value;
      }
    }

    /// <summary>Field number for the "Uid" field.</summary>
    public const int UidFieldNumber = 13;
    private uint uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerSimpleInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerSimpleInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsBanned != other.IsBanned) return false;
      if (Signature != other.Signature) return false;
      if (HeadIcon != other.HeadIcon) return false;
      if(!assistInfoList_.Equals(other.assistInfoList_)) return false;
      if (Nickname != other.Nickname) return false;
      if (!object.Equals(PlayerOutfitData, other.PlayerOutfitData)) return false;
      if (Level != other.Level) return false;
      if (LogoutTime != other.LogoutTime) return false;
      if (Platform != other.Platform) return false;
      if (PlatformUuid != other.PlatformUuid) return false;
      if (!object.Equals(HeadIconFrameInfo, other.HeadIconFrameInfo)) return false;
      if (ChatBubble != other.ChatBubble) return false;
      if (PlatformNick != other.PlatformNick) return false;
      if (PersonalCard != other.PersonalCard) return false;
      if (OnlineStatus != other.OnlineStatus) return false;
      if (Uid != other.Uid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IsBanned != false) hash ^= IsBanned.GetHashCode();
      if (Signature.Length != 0) hash ^= Signature.GetHashCode();
      if (HeadIcon != 0) hash ^= HeadIcon.GetHashCode();
      hash ^= assistInfoList_.GetHashCode();
      if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
      if (playerOutfitData_ != null) hash ^= PlayerOutfitData.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (LogoutTime != 0L) hash ^= LogoutTime.GetHashCode();
      if (Platform != global::EggLink.DanhengServer.Proto.PlatformType.Editor) hash ^= Platform.GetHashCode();
      if (PlatformUuid.Length != 0) hash ^= PlatformUuid.GetHashCode();
      if (headIconFrameInfo_ != null) hash ^= HeadIconFrameInfo.GetHashCode();
      if (ChatBubble != 0) hash ^= ChatBubble.GetHashCode();
      if (PlatformNick.Length != 0) hash ^= PlatformNick.GetHashCode();
      if (PersonalCard != 0) hash ^= PersonalCard.GetHashCode();
      if (OnlineStatus != global::EggLink.DanhengServer.Proto.FriendOnlineStatus.Offline) hash ^= OnlineStatus.GetHashCode();
      if (Uid != 0) hash ^= Uid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LogoutTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(LogoutTime);
      }
      if (HeadIcon != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(HeadIcon);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signature);
      }
      if (IsBanned != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsBanned);
      }
      if (playerOutfitData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PlayerOutfitData);
      }
      if (ChatBubble != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ChatBubble);
      }
      if (PlatformNick.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PlatformNick);
      }
      assistInfoList_.WriteTo(output, _repeated_assistInfoList_codec);
      if (Level != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Level);
      }
      if (PlatformUuid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PlatformUuid);
      }
      if (Platform != global::EggLink.DanhengServer.Proto.PlatformType.Editor) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Platform);
      }
      if (PersonalCard != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(PersonalCard);
      }
      if (Uid != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(Uid);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Nickname);
      }
      if (OnlineStatus != global::EggLink.DanhengServer.Proto.FriendOnlineStatus.Offline) {
        output.WriteRawTag(120);
        output.WriteEnum((int) OnlineStatus);
      }
      if (headIconFrameInfo_ != null) {
        output.WriteRawTag(226, 64);
        output.WriteMessage(HeadIconFrameInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LogoutTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(LogoutTime);
      }
      if (HeadIcon != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(HeadIcon);
      }
      if (Signature.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Signature);
      }
      if (IsBanned != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsBanned);
      }
      if (playerOutfitData_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(PlayerOutfitData);
      }
      if (ChatBubble != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ChatBubble);
      }
      if (PlatformNick.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(PlatformNick);
      }
      assistInfoList_.WriteTo(ref output, _repeated_assistInfoList_codec);
      if (Level != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(Level);
      }
      if (PlatformUuid.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(PlatformUuid);
      }
      if (Platform != global::EggLink.DanhengServer.Proto.PlatformType.Editor) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Platform);
      }
      if (PersonalCard != 0) {
        output.WriteRawTag(96);
        output.WriteUInt32(PersonalCard);
      }
      if (Uid != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(Uid);
      }
      if (Nickname.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(Nickname);
      }
      if (OnlineStatus != global::EggLink.DanhengServer.Proto.FriendOnlineStatus.Offline) {
        output.WriteRawTag(120);
        output.WriteEnum((int) OnlineStatus);
      }
      if (headIconFrameInfo_ != null) {
        output.WriteRawTag(226, 64);
        output.WriteMessage(HeadIconFrameInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IsBanned != false) {
        size += 1 + 1;
      }
      if (Signature.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Signature);
      }
      if (HeadIcon != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HeadIcon);
      }
      size += assistInfoList_.CalculateSize(_repeated_assistInfoList_codec);
      if (Nickname.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
      }
      if (playerOutfitData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayerOutfitData);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Level);
      }
      if (LogoutTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(LogoutTime);
      }
      if (Platform != global::EggLink.DanhengServer.Proto.PlatformType.Editor) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Platform);
      }
      if (PlatformUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlatformUuid);
      }
      if (headIconFrameInfo_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(HeadIconFrameInfo);
      }
      if (ChatBubble != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChatBubble);
      }
      if (PlatformNick.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PlatformNick);
      }
      if (PersonalCard != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PersonalCard);
      }
      if (OnlineStatus != global::EggLink.DanhengServer.Proto.FriendOnlineStatus.Offline) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OnlineStatus);
      }
      if (Uid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerSimpleInfo other) {
      if (other == null) {
        return;
      }
      if (other.IsBanned != false) {
        IsBanned = other.IsBanned;
      }
      if (other.Signature.Length != 0) {
        Signature = other.Signature;
      }
      if (other.HeadIcon != 0) {
        HeadIcon = other.HeadIcon;
      }
      assistInfoList_.Add(other.assistInfoList_);
      if (other.Nickname.Length != 0) {
        Nickname = other.Nickname;
      }
      if (other.playerOutfitData_ != null) {
        if (playerOutfitData_ == null) {
          PlayerOutfitData = new global::EggLink.DanhengServer.Proto.PlayerOutfitInfo();
        }
        PlayerOutfitData.MergeFrom(other.PlayerOutfitData);
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.LogoutTime != 0L) {
        LogoutTime = other.LogoutTime;
      }
      if (other.Platform != global::EggLink.DanhengServer.Proto.PlatformType.Editor) {
        Platform = other.Platform;
      }
      if (other.PlatformUuid.Length != 0) {
        PlatformUuid = other.PlatformUuid;
      }
      if (other.headIconFrameInfo_ != null) {
        if (headIconFrameInfo_ == null) {
          HeadIconFrameInfo = new global::EggLink.DanhengServer.Proto.HeadFrameInfo();
        }
        HeadIconFrameInfo.MergeFrom(other.HeadIconFrameInfo);
      }
      if (other.ChatBubble != 0) {
        ChatBubble = other.ChatBubble;
      }
      if (other.PlatformNick.Length != 0) {
        PlatformNick = other.PlatformNick;
      }
      if (other.PersonalCard != 0) {
        PersonalCard = other.PersonalCard;
      }
      if (other.OnlineStatus != global::EggLink.DanhengServer.Proto.FriendOnlineStatus.Offline) {
        OnlineStatus = other.OnlineStatus;
      }
      if (other.Uid != 0) {
        Uid = other.Uid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LogoutTime = input.ReadInt64();
            break;
          }
          case 16: {
            HeadIcon = input.ReadUInt32();
            break;
          }
          case 26: {
            Signature = input.ReadString();
            break;
          }
          case 32: {
            IsBanned = input.ReadBool();
            break;
          }
          case 42: {
            if (playerOutfitData_ == null) {
              PlayerOutfitData = new global::EggLink.DanhengServer.Proto.PlayerOutfitInfo();
            }
            input.ReadMessage(PlayerOutfitData);
            break;
          }
          case 48: {
            ChatBubble = input.ReadUInt32();
            break;
          }
          case 58: {
            PlatformNick = input.ReadString();
            break;
          }
          case 66: {
            assistInfoList_.AddEntriesFrom(input, _repeated_assistInfoList_codec);
            break;
          }
          case 72: {
            Level = input.ReadUInt32();
            break;
          }
          case 82: {
            PlatformUuid = input.ReadString();
            break;
          }
          case 88: {
            Platform = (global::EggLink.DanhengServer.Proto.PlatformType) input.ReadEnum();
            break;
          }
          case 96: {
            PersonalCard = input.ReadUInt32();
            break;
          }
          case 104: {
            Uid = input.ReadUInt32();
            break;
          }
          case 114: {
            Nickname = input.ReadString();
            break;
          }
          case 120: {
            OnlineStatus = (global::EggLink.DanhengServer.Proto.FriendOnlineStatus) input.ReadEnum();
            break;
          }
          case 8290: {
            if (headIconFrameInfo_ == null) {
              HeadIconFrameInfo = new global::EggLink.DanhengServer.Proto.HeadFrameInfo();
            }
            input.ReadMessage(HeadIconFrameInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LogoutTime = input.ReadInt64();
            break;
          }
          case 16: {
            HeadIcon = input.ReadUInt32();
            break;
          }
          case 26: {
            Signature = input.ReadString();
            break;
          }
          case 32: {
            IsBanned = input.ReadBool();
            break;
          }
          case 42: {
            if (playerOutfitData_ == null) {
              PlayerOutfitData = new global::EggLink.DanhengServer.Proto.PlayerOutfitInfo();
            }
            input.ReadMessage(PlayerOutfitData);
            break;
          }
          case 48: {
            ChatBubble = input.ReadUInt32();
            break;
          }
          case 58: {
            PlatformNick = input.ReadString();
            break;
          }
          case 66: {
            assistInfoList_.AddEntriesFrom(ref input, _repeated_assistInfoList_codec);
            break;
          }
          case 72: {
            Level = input.ReadUInt32();
            break;
          }
          case 82: {
            PlatformUuid = input.ReadString();
            break;
          }
          case 88: {
            Platform = (global::EggLink.DanhengServer.Proto.PlatformType) input.ReadEnum();
            break;
          }
          case 96: {
            PersonalCard = input.ReadUInt32();
            break;
          }
          case 104: {
            Uid = input.ReadUInt32();
            break;
          }
          case 114: {
            Nickname = input.ReadString();
            break;
          }
          case 120: {
            OnlineStatus = (global::EggLink.DanhengServer.Proto.FriendOnlineStatus) input.ReadEnum();
            break;
          }
          case 8290: {
            if (headIconFrameInfo_ == null) {
              HeadIconFrameInfo = new global::EggLink.DanhengServer.Proto.HeadFrameInfo();
            }
            input.ReadMessage(HeadIconFrameInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
