// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RogueTournEnterRogueCocoonSceneCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from RogueTournEnterRogueCocoonSceneCsReq.proto</summary>
  public static partial class RogueTournEnterRogueCocoonSceneCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for RogueTournEnterRogueCocoonSceneCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RogueTournEnterRogueCocoonSceneCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipSb2d1ZVRvdXJuRW50ZXJSb2d1ZUNvY29vblNjZW5lQ3NSZXEucHJvdG8a",
            "EVBISEtPTUJHUFBLLnByb3RvIsIBCiRSb2d1ZVRvdXJuRW50ZXJSb2d1ZUNv",
            "Y29vblNjZW5lQ3NSZXESHgoWY29jb29uX2NoYWxsZW5nZV90aW1lcxgHIAEo",
            "DRITCgtJQkdOTEJPRUJDRxgOIAEoDRIhCgthdmF0YXJfbGlzdBgIIAMoCzIM",
            "LlBISEtPTUJHUFBLEhgKEGRpZmZpY3VsdHlfbGV2ZWwYDSABKA0SEwoLRUlE",
            "RE1HSExQQlAYBCABKAgSEwoLUElMTUtIQ0tNRUQYBSABKA1CHqoCG0VnZ0xp",
            "bmsuRGFuaGVuZ1NlcnZlci5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.PHHKOMBGPPKReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.RogueTournEnterRogueCocoonSceneCsReq), global::EggLink.DanhengServer.Proto.RogueTournEnterRogueCocoonSceneCsReq.Parser, new[]{ "CocoonChallengeTimes", "IBGNLBOEBCG", "AvatarList", "DifficultyLevel", "EIDDMGHLPBP", "PILMKHCKMED" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RogueTournEnterRogueCocoonSceneCsReq : pb::IMessage<RogueTournEnterRogueCocoonSceneCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RogueTournEnterRogueCocoonSceneCsReq> _parser = new pb::MessageParser<RogueTournEnterRogueCocoonSceneCsReq>(() => new RogueTournEnterRogueCocoonSceneCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RogueTournEnterRogueCocoonSceneCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.RogueTournEnterRogueCocoonSceneCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueTournEnterRogueCocoonSceneCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueTournEnterRogueCocoonSceneCsReq(RogueTournEnterRogueCocoonSceneCsReq other) : this() {
      cocoonChallengeTimes_ = other.cocoonChallengeTimes_;
      iBGNLBOEBCG_ = other.iBGNLBOEBCG_;
      avatarList_ = other.avatarList_.Clone();
      difficultyLevel_ = other.difficultyLevel_;
      eIDDMGHLPBP_ = other.eIDDMGHLPBP_;
      pILMKHCKMED_ = other.pILMKHCKMED_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueTournEnterRogueCocoonSceneCsReq Clone() {
      return new RogueTournEnterRogueCocoonSceneCsReq(this);
    }

    /// <summary>Field number for the "cocoon_challenge_times" field.</summary>
    public const int CocoonChallengeTimesFieldNumber = 7;
    private uint cocoonChallengeTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CocoonChallengeTimes {
      get { return cocoonChallengeTimes_; }
      set {
        cocoonChallengeTimes_ = value;
      }
    }

    /// <summary>Field number for the "IBGNLBOEBCG" field.</summary>
    public const int IBGNLBOEBCGFieldNumber = 14;
    private uint iBGNLBOEBCG_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IBGNLBOEBCG {
      get { return iBGNLBOEBCG_; }
      set {
        iBGNLBOEBCG_ = value;
      }
    }

    /// <summary>Field number for the "avatar_list" field.</summary>
    public const int AvatarListFieldNumber = 8;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.PHHKOMBGPPK> _repeated_avatarList_codec
        = pb::FieldCodec.ForMessage(66, global::EggLink.DanhengServer.Proto.PHHKOMBGPPK.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PHHKOMBGPPK> avatarList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PHHKOMBGPPK>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.PHHKOMBGPPK> AvatarList {
      get { return avatarList_; }
    }

    /// <summary>Field number for the "difficulty_level" field.</summary>
    public const int DifficultyLevelFieldNumber = 13;
    private uint difficultyLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DifficultyLevel {
      get { return difficultyLevel_; }
      set {
        difficultyLevel_ = value;
      }
    }

    /// <summary>Field number for the "EIDDMGHLPBP" field.</summary>
    public const int EIDDMGHLPBPFieldNumber = 4;
    private bool eIDDMGHLPBP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EIDDMGHLPBP {
      get { return eIDDMGHLPBP_; }
      set {
        eIDDMGHLPBP_ = value;
      }
    }

    /// <summary>Field number for the "PILMKHCKMED" field.</summary>
    public const int PILMKHCKMEDFieldNumber = 5;
    private uint pILMKHCKMED_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PILMKHCKMED {
      get { return pILMKHCKMED_; }
      set {
        pILMKHCKMED_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RogueTournEnterRogueCocoonSceneCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RogueTournEnterRogueCocoonSceneCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CocoonChallengeTimes != other.CocoonChallengeTimes) return false;
      if (IBGNLBOEBCG != other.IBGNLBOEBCG) return false;
      if(!avatarList_.Equals(other.avatarList_)) return false;
      if (DifficultyLevel != other.DifficultyLevel) return false;
      if (EIDDMGHLPBP != other.EIDDMGHLPBP) return false;
      if (PILMKHCKMED != other.PILMKHCKMED) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CocoonChallengeTimes != 0) hash ^= CocoonChallengeTimes.GetHashCode();
      if (IBGNLBOEBCG != 0) hash ^= IBGNLBOEBCG.GetHashCode();
      hash ^= avatarList_.GetHashCode();
      if (DifficultyLevel != 0) hash ^= DifficultyLevel.GetHashCode();
      if (EIDDMGHLPBP != false) hash ^= EIDDMGHLPBP.GetHashCode();
      if (PILMKHCKMED != 0) hash ^= PILMKHCKMED.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EIDDMGHLPBP != false) {
        output.WriteRawTag(32);
        output.WriteBool(EIDDMGHLPBP);
      }
      if (PILMKHCKMED != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(PILMKHCKMED);
      }
      if (CocoonChallengeTimes != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(CocoonChallengeTimes);
      }
      avatarList_.WriteTo(output, _repeated_avatarList_codec);
      if (DifficultyLevel != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(DifficultyLevel);
      }
      if (IBGNLBOEBCG != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(IBGNLBOEBCG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EIDDMGHLPBP != false) {
        output.WriteRawTag(32);
        output.WriteBool(EIDDMGHLPBP);
      }
      if (PILMKHCKMED != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(PILMKHCKMED);
      }
      if (CocoonChallengeTimes != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(CocoonChallengeTimes);
      }
      avatarList_.WriteTo(ref output, _repeated_avatarList_codec);
      if (DifficultyLevel != 0) {
        output.WriteRawTag(104);
        output.WriteUInt32(DifficultyLevel);
      }
      if (IBGNLBOEBCG != 0) {
        output.WriteRawTag(112);
        output.WriteUInt32(IBGNLBOEBCG);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CocoonChallengeTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CocoonChallengeTimes);
      }
      if (IBGNLBOEBCG != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IBGNLBOEBCG);
      }
      size += avatarList_.CalculateSize(_repeated_avatarList_codec);
      if (DifficultyLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DifficultyLevel);
      }
      if (EIDDMGHLPBP != false) {
        size += 1 + 1;
      }
      if (PILMKHCKMED != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PILMKHCKMED);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RogueTournEnterRogueCocoonSceneCsReq other) {
      if (other == null) {
        return;
      }
      if (other.CocoonChallengeTimes != 0) {
        CocoonChallengeTimes = other.CocoonChallengeTimes;
      }
      if (other.IBGNLBOEBCG != 0) {
        IBGNLBOEBCG = other.IBGNLBOEBCG;
      }
      avatarList_.Add(other.avatarList_);
      if (other.DifficultyLevel != 0) {
        DifficultyLevel = other.DifficultyLevel;
      }
      if (other.EIDDMGHLPBP != false) {
        EIDDMGHLPBP = other.EIDDMGHLPBP;
      }
      if (other.PILMKHCKMED != 0) {
        PILMKHCKMED = other.PILMKHCKMED;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 32: {
            EIDDMGHLPBP = input.ReadBool();
            break;
          }
          case 40: {
            PILMKHCKMED = input.ReadUInt32();
            break;
          }
          case 56: {
            CocoonChallengeTimes = input.ReadUInt32();
            break;
          }
          case 66: {
            avatarList_.AddEntriesFrom(input, _repeated_avatarList_codec);
            break;
          }
          case 104: {
            DifficultyLevel = input.ReadUInt32();
            break;
          }
          case 112: {
            IBGNLBOEBCG = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 32: {
            EIDDMGHLPBP = input.ReadBool();
            break;
          }
          case 40: {
            PILMKHCKMED = input.ReadUInt32();
            break;
          }
          case 56: {
            CocoonChallengeTimes = input.ReadUInt32();
            break;
          }
          case 66: {
            avatarList_.AddEntriesFrom(ref input, _repeated_avatarList_codec);
            break;
          }
          case 104: {
            DifficultyLevel = input.ReadUInt32();
            break;
          }
          case 112: {
            IBGNLBOEBCG = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
