// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RogueMiracle.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from RogueMiracle.proto</summary>
  public static partial class RogueMiracleReflection {

    #region Descriptor
    /// <summary>File descriptor for RogueMiracle.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RogueMiracleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJSb2d1ZU1pcmFjbGUucHJvdG8ixQEKDFJvZ3VlTWlyYWNsZRIRCgljdXJf",
            "dGltZXMYCyABKA0SEQoJbWF4X3RpbWVzGAMgASgNEhIKCmR1cmFiaWxpdHkY",
            "BCABKA0SMwoLR01BRkVKRUpCSE8YAiADKAsyHi5Sb2d1ZU1pcmFjbGUuR01B",
            "RkVKRUpCSE9FbnRyeRISCgptaXJhY2xlX2lkGAEgASgNGjIKEEdNQUZFSkVK",
            "QkhPRW50cnkSCwoDa2V5GAEgASgNEg0KBXZhbHVlGAIgASgNOgI4AUIeqgIb",
            "RWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.RogueMiracle), global::EggLink.DanhengServer.Proto.RogueMiracle.Parser, new[]{ "CurTimes", "MaxTimes", "Durability", "GMAFEJEJBHO", "MiracleId" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RogueMiracle : pb::IMessage<RogueMiracle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RogueMiracle> _parser = new pb::MessageParser<RogueMiracle>(() => new RogueMiracle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RogueMiracle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.RogueMiracleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueMiracle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueMiracle(RogueMiracle other) : this() {
      curTimes_ = other.curTimes_;
      maxTimes_ = other.maxTimes_;
      durability_ = other.durability_;
      gMAFEJEJBHO_ = other.gMAFEJEJBHO_.Clone();
      miracleId_ = other.miracleId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueMiracle Clone() {
      return new RogueMiracle(this);
    }

    /// <summary>Field number for the "cur_times" field.</summary>
    public const int CurTimesFieldNumber = 11;
    private uint curTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurTimes {
      get { return curTimes_; }
      set {
        curTimes_ = value;
      }
    }

    /// <summary>Field number for the "max_times" field.</summary>
    public const int MaxTimesFieldNumber = 3;
    private uint maxTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxTimes {
      get { return maxTimes_; }
      set {
        maxTimes_ = value;
      }
    }

    /// <summary>Field number for the "durability" field.</summary>
    public const int DurabilityFieldNumber = 4;
    private uint durability_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Durability {
      get { return durability_; }
      set {
        durability_ = value;
      }
    }

    /// <summary>Field number for the "GMAFEJEJBHO" field.</summary>
    public const int GMAFEJEJBHOFieldNumber = 2;
    private static readonly pbc::MapField<uint, uint>.Codec _map_gMAFEJEJBHO_codec
        = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 18);
    private readonly pbc::MapField<uint, uint> gMAFEJEJBHO_ = new pbc::MapField<uint, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, uint> GMAFEJEJBHO {
      get { return gMAFEJEJBHO_; }
    }

    /// <summary>Field number for the "miracle_id" field.</summary>
    public const int MiracleIdFieldNumber = 1;
    private uint miracleId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MiracleId {
      get { return miracleId_; }
      set {
        miracleId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RogueMiracle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RogueMiracle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurTimes != other.CurTimes) return false;
      if (MaxTimes != other.MaxTimes) return false;
      if (Durability != other.Durability) return false;
      if (!GMAFEJEJBHO.Equals(other.GMAFEJEJBHO)) return false;
      if (MiracleId != other.MiracleId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurTimes != 0) hash ^= CurTimes.GetHashCode();
      if (MaxTimes != 0) hash ^= MaxTimes.GetHashCode();
      if (Durability != 0) hash ^= Durability.GetHashCode();
      hash ^= GMAFEJEJBHO.GetHashCode();
      if (MiracleId != 0) hash ^= MiracleId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MiracleId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MiracleId);
      }
      gMAFEJEJBHO_.WriteTo(output, _map_gMAFEJEJBHO_codec);
      if (MaxTimes != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MaxTimes);
      }
      if (Durability != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Durability);
      }
      if (CurTimes != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(CurTimes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MiracleId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MiracleId);
      }
      gMAFEJEJBHO_.WriteTo(ref output, _map_gMAFEJEJBHO_codec);
      if (MaxTimes != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(MaxTimes);
      }
      if (Durability != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Durability);
      }
      if (CurTimes != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(CurTimes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurTimes);
      }
      if (MaxTimes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxTimes);
      }
      if (Durability != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Durability);
      }
      size += gMAFEJEJBHO_.CalculateSize(_map_gMAFEJEJBHO_codec);
      if (MiracleId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MiracleId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RogueMiracle other) {
      if (other == null) {
        return;
      }
      if (other.CurTimes != 0) {
        CurTimes = other.CurTimes;
      }
      if (other.MaxTimes != 0) {
        MaxTimes = other.MaxTimes;
      }
      if (other.Durability != 0) {
        Durability = other.Durability;
      }
      gMAFEJEJBHO_.MergeFrom(other.gMAFEJEJBHO_);
      if (other.MiracleId != 0) {
        MiracleId = other.MiracleId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MiracleId = input.ReadUInt32();
            break;
          }
          case 18: {
            gMAFEJEJBHO_.AddEntriesFrom(input, _map_gMAFEJEJBHO_codec);
            break;
          }
          case 24: {
            MaxTimes = input.ReadUInt32();
            break;
          }
          case 32: {
            Durability = input.ReadUInt32();
            break;
          }
          case 88: {
            CurTimes = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MiracleId = input.ReadUInt32();
            break;
          }
          case 18: {
            gMAFEJEJBHO_.AddEntriesFrom(ref input, _map_gMAFEJEJBHO_codec);
            break;
          }
          case 24: {
            MaxTimes = input.ReadUInt32();
            break;
          }
          case 32: {
            Durability = input.ReadUInt32();
            break;
          }
          case 88: {
            CurTimes = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
