// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RogueTournLevelInfoUpdateScNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from RogueTournLevelInfoUpdateScNotify.proto</summary>
  public static partial class RogueTournLevelInfoUpdateScNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for RogueTournLevelInfoUpdateScNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RogueTournLevelInfoUpdateScNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidSb2d1ZVRvdXJuTGV2ZWxJbmZvVXBkYXRlU2NOb3RpZnkucHJvdG8aFVJv",
            "Z3VlVG91cm5MZXZlbC5wcm90bxobUm9ndWVUb3VybkxldmVsU3RhdHVzLnBy",
            "b3RvGhxSb2d1ZVRvdXJuU2V0dGxlUmVhc29uLnByb3RvIrgBCiFSb2d1ZVRv",
            "dXJuTGV2ZWxJbmZvVXBkYXRlU2NOb3RpZnkSFwoPY3VyX2xldmVsX2luZGV4",
            "GA8gASgNEikKD2xldmVsX2luZm9fbGlzdBgOIAMoCzIQLlJvZ3VlVG91cm5M",
            "ZXZlbBInCgZyZWFzb24YAiABKA4yFy5Sb2d1ZVRvdXJuU2V0dGxlUmVhc29u",
            "EiYKBnN0YXR1cxgMIAEoDjIWLlJvZ3VlVG91cm5MZXZlbFN0YXR1c0IeqgIb",
            "RWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.RogueTournLevelReflection.Descriptor, global::EggLink.DanhengServer.Proto.RogueTournLevelStatusReflection.Descriptor, global::EggLink.DanhengServer.Proto.RogueTournSettleReasonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.RogueTournLevelInfoUpdateScNotify), global::EggLink.DanhengServer.Proto.RogueTournLevelInfoUpdateScNotify.Parser, new[]{ "CurLevelIndex", "LevelInfoList", "Reason", "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RogueTournLevelInfoUpdateScNotify : pb::IMessage<RogueTournLevelInfoUpdateScNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RogueTournLevelInfoUpdateScNotify> _parser = new pb::MessageParser<RogueTournLevelInfoUpdateScNotify>(() => new RogueTournLevelInfoUpdateScNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RogueTournLevelInfoUpdateScNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.RogueTournLevelInfoUpdateScNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueTournLevelInfoUpdateScNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueTournLevelInfoUpdateScNotify(RogueTournLevelInfoUpdateScNotify other) : this() {
      curLevelIndex_ = other.curLevelIndex_;
      levelInfoList_ = other.levelInfoList_.Clone();
      reason_ = other.reason_;
      status_ = other.status_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RogueTournLevelInfoUpdateScNotify Clone() {
      return new RogueTournLevelInfoUpdateScNotify(this);
    }

    /// <summary>Field number for the "cur_level_index" field.</summary>
    public const int CurLevelIndexFieldNumber = 15;
    private uint curLevelIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurLevelIndex {
      get { return curLevelIndex_; }
      set {
        curLevelIndex_ = value;
      }
    }

    /// <summary>Field number for the "level_info_list" field.</summary>
    public const int LevelInfoListFieldNumber = 14;
    private static readonly pb::FieldCodec<global::EggLink.DanhengServer.Proto.RogueTournLevel> _repeated_levelInfoList_codec
        = pb::FieldCodec.ForMessage(114, global::EggLink.DanhengServer.Proto.RogueTournLevel.Parser);
    private readonly pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RogueTournLevel> levelInfoList_ = new pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RogueTournLevel>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::EggLink.DanhengServer.Proto.RogueTournLevel> LevelInfoList {
      get { return levelInfoList_; }
    }

    /// <summary>Field number for the "reason" field.</summary>
    public const int ReasonFieldNumber = 2;
    private global::EggLink.DanhengServer.Proto.RogueTournSettleReason reason_ = global::EggLink.DanhengServer.Proto.RogueTournSettleReason.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.RogueTournSettleReason Reason {
      get { return reason_; }
      set {
        reason_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 12;
    private global::EggLink.DanhengServer.Proto.RogueTournLevelStatus status_ = global::EggLink.DanhengServer.Proto.RogueTournLevelStatus.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.RogueTournLevelStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RogueTournLevelInfoUpdateScNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RogueTournLevelInfoUpdateScNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurLevelIndex != other.CurLevelIndex) return false;
      if(!levelInfoList_.Equals(other.levelInfoList_)) return false;
      if (Reason != other.Reason) return false;
      if (Status != other.Status) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurLevelIndex != 0) hash ^= CurLevelIndex.GetHashCode();
      hash ^= levelInfoList_.GetHashCode();
      if (Reason != global::EggLink.DanhengServer.Proto.RogueTournSettleReason.None) hash ^= Reason.GetHashCode();
      if (Status != global::EggLink.DanhengServer.Proto.RogueTournLevelStatus.None) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reason != global::EggLink.DanhengServer.Proto.RogueTournSettleReason.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Reason);
      }
      if (Status != global::EggLink.DanhengServer.Proto.RogueTournLevelStatus.None) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Status);
      }
      levelInfoList_.WriteTo(output, _repeated_levelInfoList_codec);
      if (CurLevelIndex != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(CurLevelIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reason != global::EggLink.DanhengServer.Proto.RogueTournSettleReason.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Reason);
      }
      if (Status != global::EggLink.DanhengServer.Proto.RogueTournLevelStatus.None) {
        output.WriteRawTag(96);
        output.WriteEnum((int) Status);
      }
      levelInfoList_.WriteTo(ref output, _repeated_levelInfoList_codec);
      if (CurLevelIndex != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(CurLevelIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurLevelIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurLevelIndex);
      }
      size += levelInfoList_.CalculateSize(_repeated_levelInfoList_codec);
      if (Reason != global::EggLink.DanhengServer.Proto.RogueTournSettleReason.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Reason);
      }
      if (Status != global::EggLink.DanhengServer.Proto.RogueTournLevelStatus.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RogueTournLevelInfoUpdateScNotify other) {
      if (other == null) {
        return;
      }
      if (other.CurLevelIndex != 0) {
        CurLevelIndex = other.CurLevelIndex;
      }
      levelInfoList_.Add(other.levelInfoList_);
      if (other.Reason != global::EggLink.DanhengServer.Proto.RogueTournSettleReason.None) {
        Reason = other.Reason;
      }
      if (other.Status != global::EggLink.DanhengServer.Proto.RogueTournLevelStatus.None) {
        Status = other.Status;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Reason = (global::EggLink.DanhengServer.Proto.RogueTournSettleReason) input.ReadEnum();
            break;
          }
          case 96: {
            Status = (global::EggLink.DanhengServer.Proto.RogueTournLevelStatus) input.ReadEnum();
            break;
          }
          case 114: {
            levelInfoList_.AddEntriesFrom(input, _repeated_levelInfoList_codec);
            break;
          }
          case 120: {
            CurLevelIndex = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Reason = (global::EggLink.DanhengServer.Proto.RogueTournSettleReason) input.ReadEnum();
            break;
          }
          case 96: {
            Status = (global::EggLink.DanhengServer.Proto.RogueTournLevelStatus) input.ReadEnum();
            break;
          }
          case 114: {
            levelInfoList_.AddEntriesFrom(ref input, _repeated_levelInfoList_codec);
            break;
          }
          case 120: {
            CurLevelIndex = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
