// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TarotBookGetDataScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from TarotBookGetDataScRsp.proto</summary>
  public static partial class TarotBookGetDataScRspReflection {

    #region Descriptor
    /// <summary>File descriptor for TarotBookGetDataScRsp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TarotBookGetDataScRspReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtUYXJvdEJvb2tHZXREYXRhU2NSc3AucHJvdG8aEUZMT0lDS01OTUxMLnBy",
            "b3RvGhFPRkRHT0dEQkhBQy5wcm90byKRAwoVVGFyb3RCb29rR2V0RGF0YVNj",
            "UnNwEhMKC0xFTlBJRE1QRUNQGAEgASgNEjwKC05EQ0pKUEdORkxOGAYgAygL",
            "MicuVGFyb3RCb29rR2V0RGF0YVNjUnNwLk5EQ0pKUEdORkxORW50cnkSPAoL",
            "SktFTURKSUFNSEkYCiADKAsyJy5UYXJvdEJvb2tHZXREYXRhU2NSc3AuSktF",
            "TURKSUFNSElFbnRyeRIPCgdyZXRjb2RlGAUgASgNEiEKC0hFRkpFSkhPSkVB",
            "GAIgASgLMgwuRkxPSUNLTU5NTEwSEwoLRkRDS0ZLRktITE8YByABKA0SEwoL",
            "ZW5lcmd5X2luZm8YDyABKA0SIQoLSVBOSU5PUEVLQlAYDCABKAsyDC5PRkRH",
            "T0dEQkhBQxoyChBORENKSlBHTkZMTkVudHJ5EgsKA2tleRgBIAEoDRINCgV2",
            "YWx1ZRgCIAEoDToCOAEaMgoQSktFTURKSUFNSElFbnRyeRILCgNrZXkYASAB",
            "KA0SDQoFdmFsdWUYAiABKA06AjgBQh6qAhtFZ2dMaW5rLkRhbmhlbmdTZXJ2",
            "ZXIuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EggLink.DanhengServer.Proto.FLOICKMNMLLReflection.Descriptor, global::EggLink.DanhengServer.Proto.OFDGOGDBHACReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.TarotBookGetDataScRsp), global::EggLink.DanhengServer.Proto.TarotBookGetDataScRsp.Parser, new[]{ "LENPIDMPECP", "NDCJJPGNFLN", "JKEMDJIAMHI", "Retcode", "HEFJEJHOJEA", "FDCKFKFKHLO", "EnergyInfo", "IPNINOPEKBP" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TarotBookGetDataScRsp : pb::IMessage<TarotBookGetDataScRsp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TarotBookGetDataScRsp> _parser = new pb::MessageParser<TarotBookGetDataScRsp>(() => new TarotBookGetDataScRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TarotBookGetDataScRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.TarotBookGetDataScRspReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TarotBookGetDataScRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TarotBookGetDataScRsp(TarotBookGetDataScRsp other) : this() {
      lENPIDMPECP_ = other.lENPIDMPECP_;
      nDCJJPGNFLN_ = other.nDCJJPGNFLN_.Clone();
      jKEMDJIAMHI_ = other.jKEMDJIAMHI_.Clone();
      retcode_ = other.retcode_;
      hEFJEJHOJEA_ = other.hEFJEJHOJEA_ != null ? other.hEFJEJHOJEA_.Clone() : null;
      fDCKFKFKHLO_ = other.fDCKFKFKHLO_;
      energyInfo_ = other.energyInfo_;
      iPNINOPEKBP_ = other.iPNINOPEKBP_ != null ? other.iPNINOPEKBP_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TarotBookGetDataScRsp Clone() {
      return new TarotBookGetDataScRsp(this);
    }

    /// <summary>Field number for the "LENPIDMPECP" field.</summary>
    public const int LENPIDMPECPFieldNumber = 1;
    private uint lENPIDMPECP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LENPIDMPECP {
      get { return lENPIDMPECP_; }
      set {
        lENPIDMPECP_ = value;
      }
    }

    /// <summary>Field number for the "NDCJJPGNFLN" field.</summary>
    public const int NDCJJPGNFLNFieldNumber = 6;
    private static readonly pbc::MapField<uint, uint>.Codec _map_nDCJJPGNFLN_codec
        = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 50);
    private readonly pbc::MapField<uint, uint> nDCJJPGNFLN_ = new pbc::MapField<uint, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, uint> NDCJJPGNFLN {
      get { return nDCJJPGNFLN_; }
    }

    /// <summary>Field number for the "JKEMDJIAMHI" field.</summary>
    public const int JKEMDJIAMHIFieldNumber = 10;
    private static readonly pbc::MapField<uint, uint>.Codec _map_jKEMDJIAMHI_codec
        = new pbc::MapField<uint, uint>.Codec(pb::FieldCodec.ForUInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 82);
    private readonly pbc::MapField<uint, uint> jKEMDJIAMHI_ = new pbc::MapField<uint, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<uint, uint> JKEMDJIAMHI {
      get { return jKEMDJIAMHI_; }
    }

    /// <summary>Field number for the "retcode" field.</summary>
    public const int RetcodeFieldNumber = 5;
    private uint retcode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Retcode {
      get { return retcode_; }
      set {
        retcode_ = value;
      }
    }

    /// <summary>Field number for the "HEFJEJHOJEA" field.</summary>
    public const int HEFJEJHOJEAFieldNumber = 2;
    private global::EggLink.DanhengServer.Proto.FLOICKMNMLL hEFJEJHOJEA_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.FLOICKMNMLL HEFJEJHOJEA {
      get { return hEFJEJHOJEA_; }
      set {
        hEFJEJHOJEA_ = value;
      }
    }

    /// <summary>Field number for the "FDCKFKFKHLO" field.</summary>
    public const int FDCKFKFKHLOFieldNumber = 7;
    private uint fDCKFKFKHLO_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FDCKFKFKHLO {
      get { return fDCKFKFKHLO_; }
      set {
        fDCKFKFKHLO_ = value;
      }
    }

    /// <summary>Field number for the "energy_info" field.</summary>
    public const int EnergyInfoFieldNumber = 15;
    private uint energyInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EnergyInfo {
      get { return energyInfo_; }
      set {
        energyInfo_ = value;
      }
    }

    /// <summary>Field number for the "IPNINOPEKBP" field.</summary>
    public const int IPNINOPEKBPFieldNumber = 12;
    private global::EggLink.DanhengServer.Proto.OFDGOGDBHAC iPNINOPEKBP_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::EggLink.DanhengServer.Proto.OFDGOGDBHAC IPNINOPEKBP {
      get { return iPNINOPEKBP_; }
      set {
        iPNINOPEKBP_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TarotBookGetDataScRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TarotBookGetDataScRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LENPIDMPECP != other.LENPIDMPECP) return false;
      if (!NDCJJPGNFLN.Equals(other.NDCJJPGNFLN)) return false;
      if (!JKEMDJIAMHI.Equals(other.JKEMDJIAMHI)) return false;
      if (Retcode != other.Retcode) return false;
      if (!object.Equals(HEFJEJHOJEA, other.HEFJEJHOJEA)) return false;
      if (FDCKFKFKHLO != other.FDCKFKFKHLO) return false;
      if (EnergyInfo != other.EnergyInfo) return false;
      if (!object.Equals(IPNINOPEKBP, other.IPNINOPEKBP)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LENPIDMPECP != 0) hash ^= LENPIDMPECP.GetHashCode();
      hash ^= NDCJJPGNFLN.GetHashCode();
      hash ^= JKEMDJIAMHI.GetHashCode();
      if (Retcode != 0) hash ^= Retcode.GetHashCode();
      if (hEFJEJHOJEA_ != null) hash ^= HEFJEJHOJEA.GetHashCode();
      if (FDCKFKFKHLO != 0) hash ^= FDCKFKFKHLO.GetHashCode();
      if (EnergyInfo != 0) hash ^= EnergyInfo.GetHashCode();
      if (iPNINOPEKBP_ != null) hash ^= IPNINOPEKBP.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LENPIDMPECP != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(LENPIDMPECP);
      }
      if (hEFJEJHOJEA_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HEFJEJHOJEA);
      }
      if (Retcode != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Retcode);
      }
      nDCJJPGNFLN_.WriteTo(output, _map_nDCJJPGNFLN_codec);
      if (FDCKFKFKHLO != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(FDCKFKFKHLO);
      }
      jKEMDJIAMHI_.WriteTo(output, _map_jKEMDJIAMHI_codec);
      if (iPNINOPEKBP_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(IPNINOPEKBP);
      }
      if (EnergyInfo != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(EnergyInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LENPIDMPECP != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(LENPIDMPECP);
      }
      if (hEFJEJHOJEA_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(HEFJEJHOJEA);
      }
      if (Retcode != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Retcode);
      }
      nDCJJPGNFLN_.WriteTo(ref output, _map_nDCJJPGNFLN_codec);
      if (FDCKFKFKHLO != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(FDCKFKFKHLO);
      }
      jKEMDJIAMHI_.WriteTo(ref output, _map_jKEMDJIAMHI_codec);
      if (iPNINOPEKBP_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(IPNINOPEKBP);
      }
      if (EnergyInfo != 0) {
        output.WriteRawTag(120);
        output.WriteUInt32(EnergyInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LENPIDMPECP != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LENPIDMPECP);
      }
      size += nDCJJPGNFLN_.CalculateSize(_map_nDCJJPGNFLN_codec);
      size += jKEMDJIAMHI_.CalculateSize(_map_jKEMDJIAMHI_codec);
      if (Retcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
      }
      if (hEFJEJHOJEA_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HEFJEJHOJEA);
      }
      if (FDCKFKFKHLO != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FDCKFKFKHLO);
      }
      if (EnergyInfo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EnergyInfo);
      }
      if (iPNINOPEKBP_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IPNINOPEKBP);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TarotBookGetDataScRsp other) {
      if (other == null) {
        return;
      }
      if (other.LENPIDMPECP != 0) {
        LENPIDMPECP = other.LENPIDMPECP;
      }
      nDCJJPGNFLN_.MergeFrom(other.nDCJJPGNFLN_);
      jKEMDJIAMHI_.MergeFrom(other.jKEMDJIAMHI_);
      if (other.Retcode != 0) {
        Retcode = other.Retcode;
      }
      if (other.hEFJEJHOJEA_ != null) {
        if (hEFJEJHOJEA_ == null) {
          HEFJEJHOJEA = new global::EggLink.DanhengServer.Proto.FLOICKMNMLL();
        }
        HEFJEJHOJEA.MergeFrom(other.HEFJEJHOJEA);
      }
      if (other.FDCKFKFKHLO != 0) {
        FDCKFKFKHLO = other.FDCKFKFKHLO;
      }
      if (other.EnergyInfo != 0) {
        EnergyInfo = other.EnergyInfo;
      }
      if (other.iPNINOPEKBP_ != null) {
        if (iPNINOPEKBP_ == null) {
          IPNINOPEKBP = new global::EggLink.DanhengServer.Proto.OFDGOGDBHAC();
        }
        IPNINOPEKBP.MergeFrom(other.IPNINOPEKBP);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LENPIDMPECP = input.ReadUInt32();
            break;
          }
          case 18: {
            if (hEFJEJHOJEA_ == null) {
              HEFJEJHOJEA = new global::EggLink.DanhengServer.Proto.FLOICKMNMLL();
            }
            input.ReadMessage(HEFJEJHOJEA);
            break;
          }
          case 40: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 50: {
            nDCJJPGNFLN_.AddEntriesFrom(input, _map_nDCJJPGNFLN_codec);
            break;
          }
          case 56: {
            FDCKFKFKHLO = input.ReadUInt32();
            break;
          }
          case 82: {
            jKEMDJIAMHI_.AddEntriesFrom(input, _map_jKEMDJIAMHI_codec);
            break;
          }
          case 98: {
            if (iPNINOPEKBP_ == null) {
              IPNINOPEKBP = new global::EggLink.DanhengServer.Proto.OFDGOGDBHAC();
            }
            input.ReadMessage(IPNINOPEKBP);
            break;
          }
          case 120: {
            EnergyInfo = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LENPIDMPECP = input.ReadUInt32();
            break;
          }
          case 18: {
            if (hEFJEJHOJEA_ == null) {
              HEFJEJHOJEA = new global::EggLink.DanhengServer.Proto.FLOICKMNMLL();
            }
            input.ReadMessage(HEFJEJHOJEA);
            break;
          }
          case 40: {
            Retcode = input.ReadUInt32();
            break;
          }
          case 50: {
            nDCJJPGNFLN_.AddEntriesFrom(ref input, _map_nDCJJPGNFLN_codec);
            break;
          }
          case 56: {
            FDCKFKFKHLO = input.ReadUInt32();
            break;
          }
          case 82: {
            jKEMDJIAMHI_.AddEntriesFrom(ref input, _map_jKEMDJIAMHI_codec);
            break;
          }
          case 98: {
            if (iPNINOPEKBP_ == null) {
              IPNINOPEKBP = new global::EggLink.DanhengServer.Proto.OFDGOGDBHAC();
            }
            input.ReadMessage(IPNINOPEKBP);
            break;
          }
          case 120: {
            EnergyInfo = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
