// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UpdateGroupPropertyCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EggLink.DanhengServer.Proto {

  /// <summary>Holder for reflection information generated from UpdateGroupPropertyCsReq.proto</summary>
  public static partial class UpdateGroupPropertyCsReqReflection {

    #region Descriptor
    /// <summary>File descriptor for UpdateGroupPropertyCsReq.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UpdateGroupPropertyCsReqReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5VcGRhdGVHcm91cFByb3BlcnR5Q3NSZXEucHJvdG8ijwEKGFVwZGF0ZUdy",
            "b3VwUHJvcGVydHlDc1JlcRIcChRncm91cF9wcm9wZXJ0eV92YWx1ZRgBIAEo",
            "BRIQCghncm91cF9pZBgIIAEoDRIbChNncm91cF9wcm9wZXJ0eV9uYW1lGA4g",
            "ASgJEhAKCGZsb29yX2lkGAIgASgNEhQKDGRpbWVuc2lvbl9pZBgGIAEoDUIe",
            "qgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EggLink.DanhengServer.Proto.UpdateGroupPropertyCsReq), global::EggLink.DanhengServer.Proto.UpdateGroupPropertyCsReq.Parser, new[]{ "GroupPropertyValue", "GroupId", "GroupPropertyName", "FloorId", "DimensionId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateGroupPropertyCsReq : pb::IMessage<UpdateGroupPropertyCsReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateGroupPropertyCsReq> _parser = new pb::MessageParser<UpdateGroupPropertyCsReq>(() => new UpdateGroupPropertyCsReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateGroupPropertyCsReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EggLink.DanhengServer.Proto.UpdateGroupPropertyCsReqReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGroupPropertyCsReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGroupPropertyCsReq(UpdateGroupPropertyCsReq other) : this() {
      groupPropertyValue_ = other.groupPropertyValue_;
      groupId_ = other.groupId_;
      groupPropertyName_ = other.groupPropertyName_;
      floorId_ = other.floorId_;
      dimensionId_ = other.dimensionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateGroupPropertyCsReq Clone() {
      return new UpdateGroupPropertyCsReq(this);
    }

    /// <summary>Field number for the "group_property_value" field.</summary>
    public const int GroupPropertyValueFieldNumber = 1;
    private int groupPropertyValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GroupPropertyValue {
      get { return groupPropertyValue_; }
      set {
        groupPropertyValue_ = value;
      }
    }

    /// <summary>Field number for the "group_id" field.</summary>
    public const int GroupIdFieldNumber = 8;
    private uint groupId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint GroupId {
      get { return groupId_; }
      set {
        groupId_ = value;
      }
    }

    /// <summary>Field number for the "group_property_name" field.</summary>
    public const int GroupPropertyNameFieldNumber = 14;
    private string groupPropertyName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GroupPropertyName {
      get { return groupPropertyName_; }
      set {
        groupPropertyName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "floor_id" field.</summary>
    public const int FloorIdFieldNumber = 2;
    private uint floorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FloorId {
      get { return floorId_; }
      set {
        floorId_ = value;
      }
    }

    /// <summary>Field number for the "dimension_id" field.</summary>
    public const int DimensionIdFieldNumber = 6;
    private uint dimensionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DimensionId {
      get { return dimensionId_; }
      set {
        dimensionId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateGroupPropertyCsReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateGroupPropertyCsReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GroupPropertyValue != other.GroupPropertyValue) return false;
      if (GroupId != other.GroupId) return false;
      if (GroupPropertyName != other.GroupPropertyName) return false;
      if (FloorId != other.FloorId) return false;
      if (DimensionId != other.DimensionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GroupPropertyValue != 0) hash ^= GroupPropertyValue.GetHashCode();
      if (GroupId != 0) hash ^= GroupId.GetHashCode();
      if (GroupPropertyName.Length != 0) hash ^= GroupPropertyName.GetHashCode();
      if (FloorId != 0) hash ^= FloorId.GetHashCode();
      if (DimensionId != 0) hash ^= DimensionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GroupPropertyValue != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GroupPropertyValue);
      }
      if (FloorId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FloorId);
      }
      if (DimensionId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(DimensionId);
      }
      if (GroupId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GroupId);
      }
      if (GroupPropertyName.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(GroupPropertyName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GroupPropertyValue != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GroupPropertyValue);
      }
      if (FloorId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(FloorId);
      }
      if (DimensionId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(DimensionId);
      }
      if (GroupId != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(GroupId);
      }
      if (GroupPropertyName.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(GroupPropertyName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GroupPropertyValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GroupPropertyValue);
      }
      if (GroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GroupId);
      }
      if (GroupPropertyName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GroupPropertyName);
      }
      if (FloorId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FloorId);
      }
      if (DimensionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DimensionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateGroupPropertyCsReq other) {
      if (other == null) {
        return;
      }
      if (other.GroupPropertyValue != 0) {
        GroupPropertyValue = other.GroupPropertyValue;
      }
      if (other.GroupId != 0) {
        GroupId = other.GroupId;
      }
      if (other.GroupPropertyName.Length != 0) {
        GroupPropertyName = other.GroupPropertyName;
      }
      if (other.FloorId != 0) {
        FloorId = other.FloorId;
      }
      if (other.DimensionId != 0) {
        DimensionId = other.DimensionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GroupPropertyValue = input.ReadInt32();
            break;
          }
          case 16: {
            FloorId = input.ReadUInt32();
            break;
          }
          case 48: {
            DimensionId = input.ReadUInt32();
            break;
          }
          case 64: {
            GroupId = input.ReadUInt32();
            break;
          }
          case 114: {
            GroupPropertyName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GroupPropertyValue = input.ReadInt32();
            break;
          }
          case 16: {
            FloorId = input.ReadUInt32();
            break;
          }
          case 48: {
            DimensionId = input.ReadUInt32();
            break;
          }
          case 64: {
            GroupId = input.ReadUInt32();
            break;
          }
          case 114: {
            GroupPropertyName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
